###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.212.0Release
# Tag = production/release/21.212.0-0-g0676a0e3
############################################################################################


from .accumulator import Accumulator as Accumulator
from .bitstream import BitStream as BitStream
from .crc_calculator import CrcCalculator as CrcCalculator
from .decoder import Decoder as Decoder
from .encoder import Encoder as Encoder
from .fit import BASE_TYPE as BASE_TYPE, BASE_TYPE_DEFINITIONS as BASE_TYPE_DEFINITIONS
from .hr_mesg_utils import expand_heart_rates as expand_heart_rates
from .profile import Profile as Profile
from .stream import Stream as Stream
from .util import (
    FIT_EPOCH_S as FIT_EPOCH_S,
    convert_datetime_to_timestamp as convert_datetime_to_timestamp,
    convert_timestamp_to_datetime as convert_timestamp_to_datetime,
    BASE_TYPE_TO_FIELD_TYPE as BASE_TYPE_TO_FIELD_TYPE,
    FIELD_TYPE_TO_BASE_TYPE as FIELD_TYPE_TO_BASE_TYPE,
)

__version__: str
