###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.214.0Release
# Tag = production/release/21.214.0-0-g47b86b1f
############################################################################################


class AccumulatedField:
    def __init__(self, value: int = 0) -> None: ...
    def accumulate(self, value: int, bits: int) -> int: ...

class Accumulator:
    def __init__(self) -> None: ...
    def createAccumulatedField(self, mesg_num: int, field_num: int, value: int) -> AccumulatedField: ...
    def accumulate(self, mesg_num: int, field_num: int, value: int, bits: int) -> int: ...
