###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.213.0Release
# Tag = production/release/21.213.0-0-g9e10ea9c
############################################################################################


from typing import Any

class BitStream:
    def __init__(self, data: Any, base_type: int) -> None: ...
    def bits_available(self) -> int: ...
    def has_bits_available(self) -> bool: ...
    def reset(self) -> None: ...
    def read_bit(self) -> int: ...
    def read_bits(self, num_bits: int) -> int: ...
