'''bitstream.py: Contains BitStream class which handles reading streams of data bit by bit '''

###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.202.0Release
# Tag = production/release/21.202.0-0-g9a57aebc
############################################################################################


from . import fit as FIT


class BitStream:
    '''
    A class that represents a stream of binary data from a chunk of data.

    Internal state model:
        _data is set at construction time and holds the raw element list for the
        lifetime of the object.  _array starts as None and is only initialised
        lazily the first time a sub-element read (read_bit or a partial
        read_bits) is required.  While _array is None the fast path in
        read_bits can service full-element reads directly from _data without
        decomposing values into individual bytes.

    Attributes:
        _data: The raw list of typed elements supplied at construction.
               Never None after __init__ completes.
        _array: Alias into _data used by the slow (bit-by-bit) path.
                None until the first sub-element read triggers lazy
                initialisation; reset back to None by reset().
        _current_array_position: Current read index within _array (slow path only).
        _bits_per_position: Number of bits in each element of _data
                            (base_type size × 8).
        _current_byte: The element currently being consumed bit-by-bit (slow path).
        _current_bit: Number of bits already consumed from _current_byte (slow path).
        _bits_available: Remaining number of bits left unread in the stream.
    '''
    __slots__ = ('_data', '_array', '_current_array_position', '_bits_per_position',
                 '_current_byte', '_current_bit', '_bits_available')
    def __init__(self, data, base_type):
        self._data = None
        self._array = None
        self._current_array_position = 0
        self._bits_per_position = 0
        self._current_byte = 0
        self._current_bit = 0
        self._bits_available = 0

        self._data = data if isinstance(data, list) else [data]
        base_type_size = FIT.BASE_TYPE_DEFINITIONS[base_type]['size']
        self._bits_per_position = base_type_size * 8
        self.reset()

    def bits_available(self):
        '''Returns the number of bits left in the data.'''
        return self._bits_available

    def has_bits_available(self):
        '''Returns true if the data has bits available.'''
        return self._bits_available > 0

    def reset(self):
        '''Resets the bitstream to the start of the data and resets the bits available.'''
        self._array = None
        self._current_array_position = 0
        self._bits_available = self._bits_per_position * len(self._data)
        self._current_byte = 0
        self._current_bit = 0

    def read_bit(self):
        '''Reads the next bit if possible.'''
        if self.has_bits_available() is False:
            self.__raise_error()

        if self._array is None:
            self._array = self._data
            self._current_array_position = len(self._data) - (self._bits_available // self._bits_per_position)
            self.__next_byte()

        if self._current_bit >= self._bits_per_position:
            self.__next_byte()

        bit = self._current_byte & 0x01
        self._current_byte = (self._current_byte >> 1)
        self._current_bit += 1
        self._bits_available -= 1

        return bit

    def read_bits(self, number_bits_to_read):
        '''Reads the specificed number of bits if possible.'''
        # Fast path: if reading exactly one value's worth of bits and array hasn't been
        # initialized yet, index _data directly without decomposing into bytes.
        if number_bits_to_read == self._bits_per_position and self._array is None:
            if self._bits_available <= 0:
                self.__raise_error()
            index = len(self._data) - (self._bits_available // self._bits_per_position)
            value = self._data[index] & ((1 << self._bits_per_position) - 1)
            self._bits_available -= self._bits_per_position
            return value

        value = 0

        for i in range(number_bits_to_read):
            value |= self.read_bit() << i

        return value

    def __next_byte(self):
        if self._current_array_position >= len(self._array):
            self.__raise_error()

        self._current_byte = self._array[self._current_array_position]
        self._current_array_position += 1
        self._current_bit = 0

    def __raise_error(self):
        raise IndexError('FIT Runtime Error, no bits available.')