###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.213.0Release
# Tag = production/release/21.213.0-0-g9e10ea9c
############################################################################################


from typing import Union

class CrcCalculator:
    def __init__(self) -> None: ...
    def get_crc(self) -> int: ...
    def add_bytes(self, buffer: Union[bytes, bytearray], start: int, end: int) -> int: ...
    @staticmethod
    def calculate_crc(buffer: Union[bytes, bytearray], start: int, end: int) -> int: ...
