###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.212.0Release
# Tag = production/release/21.212.0-0-g0676a0e3
############################################################################################


from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

from .stream import Stream
from .mesgs import FitMessages

class DecodeMode(Enum):
    NORMAL = 1
    SKIP_HEADER = 2
    DATA_ONLY = 3

MesgListener = Callable[[int, Dict[str, Any]], None]
MesgDefinitionListener = Callable[[Dict[str, Any]], None]
FieldDescriptionListener = Callable[[int, Dict[str, Any], Dict[str, Any]], None]

class FileHeader:
    header_size: int
    protocol_version: int
    profile_version: int
    data_size: int
    data_type: List[bytes]
    header_crc: int
    file_total_size: int
    def get_dict(self) -> Dict[str, Any]: ...

class Decoder:
    def __init__(self, stream: Stream) -> None: ...
    def is_fit(self) -> bool: ...
    def check_integrity(self) -> bool: ...
    def read(
        self,
        apply_scale_and_offset: bool = True,
        convert_datetimes_to_dates: bool = True,
        convert_types_to_strings: bool = True,
        enable_crc_check: bool = True,
        expand_sub_fields: bool = True,
        expand_components: bool = True,
        merge_heart_rates: bool = True,
        mesg_listener: Optional[MesgListener] = None,
        mesg_definition_listener: Optional[MesgDefinitionListener] = None,
        field_description_listener: Optional[FieldDescriptionListener] = None,
        decode_mode: DecodeMode = ...,
    ) -> Tuple[FitMessages, List[Exception]]: ...
    def read_file_header(self, reset: bool, decode_mode: DecodeMode = ...) -> FileHeader: ...
    def get_num_messages(self) -> int: ...