###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.212.0Release
# Tag = production/release/21.212.0-0-g0676a0e3
############################################################################################


from typing import Any, Dict, Optional, Union

from .mesgs import DeveloperDataIdMesg, FieldDescriptionMesg

FieldDescription = Dict[str, Union[DeveloperDataIdMesg, FieldDescriptionMesg]]

class Encoder:
    def __init__(
        self,
        field_descriptions: Optional[Dict[int, FieldDescription]] = None,
    ) -> None: ...
    def close(self) -> bytes: ...
    def write_mesg(self, mesg: Dict[str, Any]) -> "Encoder": ...
    def on_mesg(self, mesg_num: int, mesg: Dict[str, Any]) -> "Encoder": ...
    def add_developer_field(
        self,
        key: int,
        developer_data_id_mesg: DeveloperDataIdMesg,
        field_description_mesg: FieldDescriptionMesg,
    ) -> "Encoder": ...
