'''encoder.py: Contains the Encoder class which is used to encode FIT files.'''

###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.218.0Release
# Tag = production/release/21.218.0-0-g96fee6d7
############################################################################################


import struct

from . import CrcCalculator
from . import fit as FIT
from .profile import Profile
from .util import convert_datetime_to_timestamp
from .mesg_definition import _MesgDefinition
from .output_stream import _OutputStream

_HEADER_WITH_CRC_SIZE = 14
_HEADER_WITHOUT_CRC_SIZE = 12

_FLOATING_POINT_FIELD_TYPES = ["float32", "float64"]


class Encoder:
    """A class for encoding FIT files."""

    def __init__(self, field_descriptions=None):
        """Creates a FIT File Encoder.

        Args:
            field_descriptions: (optional, default None) A dict of field descriptions keyed by
                developer field key, each containing a developer_data_id_mesg and
                field_description_mesg.
        """
        self._output_stream = _OutputStream()
        self._local_mesg_definitions = [None] * 16
        self._next_local_mesg_num = 0
        self._field_descriptions = {}

        if field_descriptions:
            for key, desc in field_descriptions.items():
                self.add_developer_field(
                    key,
                    desc.get('developer_data_id_mesg'),
                    desc.get('field_description_mesg'),
                )

        self._write_empty_file_header()

    def close(self):
        """Closes the encoder and returns the file data.

        Returns:
            bytes: The encoded FIT file data.
        """
        self._update_file_header()
        self._write_file_crc()
        return self._output_stream.data

    def write_mesg(self, mesg):
        """Encodes a mesg into the file.

        Args:
            mesg: The message data. Must contain a 'mesg_num' key.

        Returns:
            Encoder: self
        """
        if 'mesg_num' not in mesg:
            raise ValueError("mesg must contain a 'mesg_num' key")
        return self.on_mesg(mesg['mesg_num'], mesg)

    def on_mesg(self, mesg_num, mesg):
        """Encodes a mesg into the file.

        This method can be used as a Decoder mesg_listener callback.

        Args:
            mesg_num: The message number for this message.
            mesg: The message data.

        Returns:
            Encoder: self
        """
        try:
            mesg_definition = self._create_mesg_definition(mesg_num, mesg)
            local_mesg_definition = self._find_local_mesg_definition(mesg_definition)

            if local_mesg_definition is not None:
                mesg_definition = local_mesg_definition
            else:
                mesg_definition.local_mesg_num = self._next_local_mesg_num & FIT.LOCAL_MESG_NUM_MASK
                self._next_local_mesg_num += 1
                self._write_mesg_definition(mesg_definition)

            # Write message header
            self._output_stream.write_uint8(mesg_definition.local_mesg_num)

            # Write field values
            for field_definition in mesg_definition.field_definitions:
                values = self._transform_values(mesg.get(field_definition['name']), field_definition)
                self._output_stream.write(values, field_definition['base_type'])

            # Write developer field values
            for developer_field_definition in mesg_definition.developer_field_definitions:
                dev_fields = mesg.get('developer_fields', {})
                values = self._transform_values(dev_fields.get(developer_field_definition['key']), developer_field_definition)
                self._output_stream.write(values, developer_field_definition['base_type'])

        except Exception as e:
            raise ValueError(f"Could not write Message: {e}") from e

        return self

    def add_developer_field(self, key, developer_data_id_mesg, field_description_mesg):
        """Adds a Developer Data Field Description and associated Developer Data Id Message to the Encoder.

        This provides the Encoder with the context required to write Developer Fields to the output stream.
        This method does not write the messages to the output stream.
        This method can be used as a Decoder field_description_listener callback.

        Args:
            key: The key for this developer field.
            developer_data_id_mesg: The Developer Data Id mesg.
            field_description_mesg: The Field Description mesg.

        Returns:
            Encoder: self
        """
        if developer_data_id_mesg is None:
            raise ValueError("addDeveloperField() - developer_data_id_mesg is None")
        if field_description_mesg is None:
            raise ValueError("addDeveloperField() - field_description_mesg is None")

        if developer_data_id_mesg.get('developer_data_index') is None or field_description_mesg.get('developer_data_index') is None:
            raise ValueError("addDeveloperField() - one or more developer_data_index values are None.")

        if developer_data_id_mesg['developer_data_index'] != field_description_mesg['developer_data_index']:
            raise ValueError("addDeveloperField() - developer_data_index values do not match.")

        self._field_descriptions[key] = {
            'developer_data_id_mesg': developer_data_id_mesg,
            'field_description_mesg': field_description_mesg,
        }
        return self

    def _write_empty_file_header(self):
        for _ in range(_HEADER_WITH_CRC_SIZE):
            self._output_stream.write_uint8(0)

    def _update_file_header(self):
        header = bytearray(_HEADER_WITH_CRC_SIZE)

        # Header size
        header[0] = _HEADER_WITH_CRC_SIZE

        # Protocol version (2.0 => 0x20)
        header[1] = 0x20

        # Profile version
        profile_version = Profile['version']['major'] * 1000 + Profile['version']['minor']
        struct.pack_into('<H', header, 2, profile_version)

        # Data size
        data_size = self._output_stream.length - _HEADER_WITH_CRC_SIZE
        struct.pack_into('<I', header, 4, data_size)

        # Data type ".FIT"
        header[8] = 0x2E
        header[9] = 0x46
        header[10] = 0x49
        header[11] = 0x54

        # Header CRC
        crc = CrcCalculator.calculate_crc(header, 0, _HEADER_WITHOUT_CRC_SIZE)
        struct.pack_into('<H', header, 12, crc)

        self._output_stream.set_bytes(header, 0)

    def _write_file_crc(self):
        crc = CrcCalculator.calculate_crc(self._output_stream.data, 0, self._output_stream.length)
        self._output_stream.write_uint16(crc)

    def _transform_values(self, value, field_definition):
        values = value if isinstance(value, list) else [value]
        return [self._transform_value(v, field_definition) for v in values]

    def _transform_value(self, value, field_definition):
        field_type = field_definition['type']
        base_type = field_definition['base_type']
        invalid = FIT.BASE_TYPE_DEFINITIONS[base_type]['invalid']

        try:
            # Not a number, string, date, or bool => invalid
            if FIT.is_not_number_string_date_or_boolean(value):
                raise ValueError("Value is not a number, string, date, or boolean")

            # Numeric field
            if field_type in FIT.NUMERIC_FIELD_TYPES:
                if FIT.is_string(value):
                    value = float(value) if '.' in value else int(value)
                elif FIT.is_boolean(value):
                    raise ValueError("Boolean value not allowed for numeric field")
                elif not FIT.is_numeric(value):
                    raise ValueError("Value is not numeric for numeric field")

                has_scale_or_offset = (
                    field_definition['scale'] != FIT.FIELD_DEFAULT_SCALE
                    or field_definition['offset'] != FIT.FIELD_DEFAULT_OFFSET
                )

                if has_scale_or_offset:
                    scaled = self._unapply_scale_and_offset(
                        value, field_definition['scale'], field_definition['offset']
                    )
                    return scaled if field_type in _FLOATING_POINT_FIELD_TYPES else round(scaled)

                return value

            # DateTime field
            if field_type in ('date_time', 'local_date_time'):
                if FIT.is_date(value):
                    return convert_datetime_to_timestamp(value)
                if not FIT.is_numeric(value):
                    raise ValueError("Value is not numeric or date for date_time field")
                return value

            # String field
            if field_type == 'string':
                if not FIT.is_string(value):
                    raise ValueError("Value is not a string for string field")
                return value

            # Profile type field - try numeric passthrough first
            if FIT.is_numeric(value):
                return value

            # Look up string value in profile types
            profile_type = Profile['types'].get(field_type, {})
            for type_key, type_value in profile_type.items():
                if type_value == value:
                    return type_key

            raise ValueError(f'Value "{value}" could not be mapped to profile type "{field_type}"')

        except Exception as exception:
            raise ValueError(f'Could not convert "{value}" to "{field_type}": {exception}')

    @staticmethod
    def _unapply_scale_and_offset(value, scale, offset):
        return (value + offset) * scale

    def _create_mesg_definition(self, mesg_num, mesg):
        """Creates a MesgDefinition from the mesg_num and mesg.

        Args:
            mesg_num: The mesg number for this message.
            mesg: The message data.

        Returns:
            _MesgDefinition: The created message definition.
        """
        return _MesgDefinition(mesg_num, mesg, field_descriptions=self._field_descriptions)

    def _find_local_mesg_definition(self, mesg_definition):
        """Returns the active local mesg definition equivalent to mesg_definition, if any.

        Args:
            mesg_definition: The candidate message definition to match.

        Returns:
            _MesgDefinition | None: The matching active local mesg definition, if present.
        """
        for local_def in self._local_mesg_definitions:
            if local_def is not None and local_def.equals(mesg_definition):
                return local_def
        return None

    def _write_mesg_definition(self, mesg_definition):
        """Writes the mesg_definition to the output stream.

        Args:
            mesg_definition: The mesg definition to write.
        """
        mesg_definition.write(self._output_stream)
        self._local_mesg_definitions[mesg_definition.local_mesg_num] = mesg_definition