'''fit.py: Contains base type defintions and conversion functions compliant with the FIT Protocol.'''

###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.201.0Release
# Tag = production/release/21.201.0-0-g39a0a60c
############################################################################################


from datetime import datetime
import math

LOCAL_MESG_NUM_MASK = 0x0F
MESG_DEFINITION_MASK = 0x40
DEV_DATA_MASK = 0x20
ARCH_LITTLE_ENDIAN = 0x00
MAX_FIELD_SIZE = 255
FIELD_DEFAULT_SCALE = 1
FIELD_DEFAULT_OFFSET = 0

BASE_TYPE = {
    "ENUM": 0x00,
    "SINT8": 0x01,
    "UINT8": 0x02,
    "SINT16": 0x03,
    "UINT16": 0x04,
    "SINT32": 0x05,
    "UINT32": 0x06,
    "STRING": 0x07,
    "FLOAT32": 0x08,
    "FLOAT64": 0x09,
    "UINT8Z": 0x0A,
    "UINT16Z": 0x0B,
    "UINT32Z": 0x0C,
    "BYTE": 0x0D,
    "SINT64": 0x0E,
    "UINT64": 0x0F,
    "UINT64Z": 0x10
}

FIELD_TYPE_TO_BASE_TYPE = {
    "enum": BASE_TYPE['ENUM'],
    "sint8": BASE_TYPE['SINT8'],
    "uint8": BASE_TYPE['UINT8'],
    "sint16": BASE_TYPE['SINT16'],
    "uint16": BASE_TYPE['UINT16'],
    "sint32": BASE_TYPE['SINT32'],
    "uint32": BASE_TYPE['UINT32'],
    "string": BASE_TYPE['STRING'],
    "float32": BASE_TYPE['FLOAT32'],
    "float64": BASE_TYPE['FLOAT64'],
    "uint8z": BASE_TYPE['UINT8Z'],
    "uint16z": BASE_TYPE['UINT16Z'],
    "uint32z": BASE_TYPE['UINT32Z'],
    "byte": BASE_TYPE['BYTE'],
    "sint64": BASE_TYPE['SINT64'],
    "uint64": BASE_TYPE['UINT64'],
    "uint64z": BASE_TYPE['UINT64Z']
}

BASE_TYPE_TO_FIELD_TYPE = {
    BASE_TYPE['ENUM']: 'enum',
    BASE_TYPE['SINT8']: 'sint8',
    BASE_TYPE['UINT8']: 'uint8',
    BASE_TYPE['SINT16']: 'sint16',
    BASE_TYPE['UINT16']: 'uint16',
    BASE_TYPE['SINT32']: 'sint32',
    BASE_TYPE['UINT32']: 'uint32',
    BASE_TYPE['STRING']: 'string',
    BASE_TYPE['FLOAT32']: 'float32',
    BASE_TYPE['FLOAT64']: 'float64',
    BASE_TYPE['UINT8Z']: 'uint8z',
    BASE_TYPE['UINT16Z']: 'uint16z',
    BASE_TYPE['UINT32Z']: 'uint32z',
    BASE_TYPE['BYTE']: 'byte',
    BASE_TYPE['SINT64']: 'sint64',
    BASE_TYPE['UINT64']: 'uint64',
    BASE_TYPE['UINT64Z']: 'uint64z',
}

BASE_TYPE_DEFINITIONS = {
    0x00: {'size': 1, 'type': BASE_TYPE["ENUM"], 'signed': False, 'type_code': 'B', 'invalid': 0xFF, 'endian_flag': 0x00},
    0x01: {'size': 1, 'type': BASE_TYPE["SINT8"], 'signed': True, 'type_code': 'b', 'invalid': 0x7F, 'endian_flag': 0x00},
    0x02: {'size': 1, 'type': BASE_TYPE["UINT8"], 'signed': False, 'type_code': 'B', 'invalid': 0xFF, 'endian_flag': 0x00},
    0x03: {'size': 2, 'type': BASE_TYPE["SINT16"], 'signed': True, 'type_code': 'h', 'invalid': 0x7FFF, 'endian_flag': 0x80},
    0x04: {'size': 2, 'type': BASE_TYPE["UINT16"], 'signed': False, 'type_code': 'H', 'invalid': 0xFFFF, 'endian_flag': 0x80},
    0x05: {'size': 4, 'type': BASE_TYPE["SINT32"], 'signed': True, 'type_code': 'i', 'invalid': 0x7FFFFFFF, 'endian_flag': 0x80},
    0x06: {'size': 4, 'type': BASE_TYPE["UINT32"], 'signed': False, 'type_code': 'I', 'invalid': 0xFFFFFFFF, 'endian_flag': 0x80},
    0x07: {'size': 1, 'type': BASE_TYPE["STRING"], 'signed': False, 'type_code': 's', 'invalid': 0x00, 'endian_flag': 0x00},
    0x08: {'size': 4, 'type': BASE_TYPE["FLOAT32"], 'signed': True, 'type_code': 'f', 'invalid': 0xFFFFFFFF, 'endian_flag': 0x80},
    0x09: {'size': 8, 'type': BASE_TYPE["FLOAT64"], 'signed': True, 'type_code': 'd', 'invalid': 0xFFFFFFFFFFFFFFFF, 'endian_flag': 0x80},
    0x0A: {'size': 1, 'type': BASE_TYPE["UINT8Z"], 'signed': False, 'type_code': 'B', 'invalid': 0x00, 'endian_flag': 0x00},
    0x0B: {'size': 2, 'type': BASE_TYPE["UINT16Z"], 'signed': False, 'type_code': 'H', 'invalid': 0x0000, 'endian_flag': 0x80},
    0x0C: {'size': 4, 'type': BASE_TYPE["UINT32Z"], 'signed': False, 'type_code': 'I', 'invalid': 0x00000000, 'endian_flag': 0x80},
    0x0D: {'size': 1, 'type': BASE_TYPE["BYTE"], 'signed': False, 'type_code': 'B', 'invalid': 0xFF, 'endian_flag': 0x00},
    0x0E: {'size': 8, 'type': BASE_TYPE["SINT64"], 'signed': True, 'type_code': 'q', 'invalid': 0x7FFFFFFFFFFFFFFF, 'endian_flag': 0x80},
    0x0F: {'size': 8, 'type': BASE_TYPE["UINT64"], 'signed': False, 'type_code': 'Q', 'invalid': 0xFFFFFFFFFFFFFFFF, 'endian_flag': 0x80},
    0x10: {'size': 8, 'type': BASE_TYPE["UINT64Z"], 'signed': False, 'type_code': 'Q', 'invalid': 0x0000000000000000, 'endian_flag': 0x80},
}

BASE_TYPE_MASK = 0x1F

NUMERIC_FIELD_TYPES = [
    "sint8",
    "uint8",
    "sint16",
    "uint16",
    "sint32",
    "uint32",
    "float32",
    "float64",
    "uint8z",
    "uint16z",
    "uint32z",
    "byte",
    "sint64",
    "uint64",
    "uint64z"
]

def is_none(obj):
    """Return True if obj is None."""
    return obj is None


def is_boolean(obj):
    """Return True if obj is a bool."""
    return isinstance(obj, bool)


def is_date(obj):
    """Return True if obj is a datetime instance."""
    return isinstance(obj, datetime)


def is_string(obj):
    """Return True if obj is a str."""
    return isinstance(obj, str)


def is_numeric(obj):
    """Return True if obj is a finite number or a parseable numeric string (not bool)."""
    if isinstance(obj, bool):
        return False
    if isinstance(obj, int):
        return True
    if isinstance(obj, float):
        return math.isfinite(obj)
    try:
        return math.isfinite(float(obj))
    except (ValueError, TypeError):
        return False


def is_number_string_date_or_boolean(obj):
    """Return True if obj is a number, string, datetime, or bool."""
    if obj is None:
        return False
    return isinstance(obj, (int, float, str, bool, datetime))


def is_not_number_string_date_or_boolean(obj):
    """Return True if obj is NOT a number, string, datetime, or bool."""
    return not is_number_string_date_or_boolean(obj)
