###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.214.0Release
# Tag = production/release/21.214.0-0-g47b86b1f
############################################################################################


from typing import Any, Dict, List

BASE_TYPE: Dict[str, int]

BASE_TYPE_DEFINITIONS: Dict[int, Dict[str, Any]]

FIELD_TYPE_TO_BASE_TYPE: Dict[str, int]

BASE_TYPE_TO_FIELD_TYPE: Dict[int, str]

LOCAL_MESG_NUM_MASK: int
MESG_DEFINITION_MASK: int
DEV_DATA_MASK: int
ARCH_LITTLE_ENDIAN: int
MAX_FIELD_SIZE: int
FIELD_DEFAULT_SCALE: int
FIELD_DEFAULT_OFFSET: int
BASE_TYPE_MASK: int

NUMERIC_FIELD_TYPES: List[str]

def is_none(value: Any) -> bool: ...
def is_boolean(value: Any) -> bool: ...
def is_numeric(value: Any) -> bool: ...
def is_date(value: Any) -> bool: ...
def is_string(value: Any) -> bool: ...
def is_number_string_date_or_boolean(value: Any) -> bool: ...
def is_not_number_string_date_or_boolean(value: Any) -> bool: ...
