###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.212.0Release
# Tag = production/release/21.212.0-0-g0676a0e3
############################################################################################


from typing import List

from .mesgs import HrMesg, RecordMesg

def merge_heart_rates(
    hr_mesgs: List[HrMesg],
    record_mesgs: List[RecordMesg],
) -> None: ...

def expand_heart_rates(hr_mesgs: List[HrMesg]) -> List[RecordMesg]: ...
