###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.214.0Release
# Tag = production/release/21.214.0-0-g47b86b1f
############################################################################################


from datetime import datetime
from typing import Any, Dict, List, Optional, Union

try:
    from typing import TypedDict
except ImportError:
    from typing_extensions import TypedDict  # type: ignore[assignment]

from .types import *


class FitMesg(TypedDict, total=False):
    """Base TypedDict for all decoded FIT messages."""
    mesg_num: int
    developer_fields: Dict[int, Any]



# Must be first message in file.
class FileIdMesg(FitMesg, total=False):
    type: File
    manufacturer: Manufacturer
    product: int
    favero_product: FaveroProduct
    garmin_product: GarminProduct
    serial_number: int
    # Only set for files that are can be created/erased.
    time_created: Union[int, datetime]
    # Only set for files that are not created/erased.
    number: int
    # Optional free form string to indicate the devices name or model
    product_name: StringValue



class FileCreatorMesg(FitMesg, total=False):
    software_version: int
    hardware_version: int



class TimestampCorrelationMesg(FitMesg, total=False):
    # Whole second part of UTC timestamp at the time the system timestamp was recorded.
    timestamp: Union[int, datetime]
    # Fractional part of the UTC timestamp at the time the system timestamp was recorded.
    fractional_timestamp: float
    # Whole second part of the system timestamp
    system_timestamp: Union[int, datetime]
    # Fractional part of the system timestamp
    fractional_system_timestamp: float
    # timestamp epoch expressed in local time used to convert timestamps to local time
    local_timestamp: Union[int, datetime]
    # Millisecond part of the UTC timestamp at the time the system timestamp was recorded.
    timestamp_ms: int
    # Millisecond part of the system timestamp
    system_timestamp_ms: int



class SoftwareMesg(FitMesg, total=False):
    message_index: MessageIndex
    version: float
    part_number: StringValue



class SlaveDeviceMesg(FitMesg, total=False):
    manufacturer: Manufacturer
    product: int
    favero_product: FaveroProduct
    garmin_product: GarminProduct



class CapabilitiesMesg(FitMesg, total=False):
    # Use language_bits_x types where x is index of array.
    languages: Union[int, List[Optional[int]]]
    # Use sport_bits_x types where x is index of array.
    sports: Union[SportBits0, List[Optional[SportBits0]]]
    workouts_supported: WorkoutCapabilities
    connectivity_supported: ConnectivityCapabilities



class FileCapabilitiesMesg(FitMesg, total=False):
    message_index: MessageIndex
    type: File
    flags: FileFlags
    directory: StringValue
    max_count: int
    max_size: int



class MesgCapabilitiesMesg(FitMesg, total=False):
    message_index: MessageIndex
    file: File
    mesg_num: MesgNum
    count_type: MesgCount
    count: int
    num_per_file: int
    max_per_file: int
    max_per_file_type: int



class FieldCapabilitiesMesg(FitMesg, total=False):
    message_index: MessageIndex
    file: File
    mesg_num: MesgNum
    field_num: int
    count: int



class DeviceSettingsMesg(FitMesg, total=False):
    # Index into time zone arrays.
    active_time_zone: int
    # Offset from system time. Required to convert timestamp from system time to UTC.
    utc_offset: int
    # Offset from system time.
    time_offset: Union[int, List[Optional[int]]]
    # Display mode for the time
    time_mode: Union[TimeMode, List[Optional[TimeMode]]]
    # timezone offset in 1/4 hour increments
    time_zone_offset: Union[float, List[Optional[float]]]
    # Mode for backlight
    backlight_mode: BacklightMode
    # Enabled state of the activity tracker functionality
    activity_tracker_enabled: bool
    # UTC timestamp used to set the devices clock and date
    clock_time: Union[int, datetime]
    # Bitfield to configure enabled screens for each supported loop
    pages_enabled: Union[int, List[Optional[int]]]
    # Enabled state of the move alert
    move_alert_enabled: bool
    # Display mode for the date
    date_mode: DateMode
    display_orientation: DisplayOrientation
    mounting_side: Side
    # Bitfield to indicate one page as default for each supported loop
    default_page: Union[int, List[Optional[int]]]
    # Minimum steps before an autosync can occur
    autosync_min_steps: int
    # Minimum minutes before an autosync can occur
    autosync_min_time: int
    # Enable auto-detect setting for the lactate threshold feature.
    lactate_threshold_autodetect_enabled: bool
    # Automatically upload using BLE
    ble_auto_upload_enabled: bool
    # Helps to conserve battery by changing modes
    auto_sync_frequency: AutoSyncFrequency
    # Allows setting specific activities auto-activity detect enabled/disabled settings
    auto_activity_detect: AutoActivityDetect
    # Number of screens configured to display
    number_of_screens: int
    # Smart Notification display orientation
    smart_notification_display_orientation: DisplayOrientation
    tap_interface: Switch
    # Used to hold the tap threshold setting
    tap_sensitivity: TapSensitivity



class UserProfileMesg(FitMesg, total=False):
    message_index: MessageIndex
    # Used for Morning Report greeting
    friendly_name: StringValue
    gender: Gender
    age: int
    height: float
    weight: float
    language: Language
    elev_setting: DisplayMeasure
    weight_setting: DisplayMeasure
    resting_heart_rate: int
    default_max_running_heart_rate: int
    default_max_biking_heart_rate: int
    default_max_heart_rate: int
    hr_setting: DisplayHeart
    speed_setting: DisplayMeasure
    dist_setting: DisplayMeasure
    power_setting: DisplayPower
    activity_class: ActivityClass
    position_setting: DisplayPosition
    temperature_setting: DisplayMeasure
    local_id: UserLocalId
    global_id: Union[int, List[Optional[int]]]
    # Typical wake time
    wake_time: LocaltimeIntoDay
    # Typical bed time
    sleep_time: LocaltimeIntoDay
    height_setting: DisplayMeasure
    # User defined running step length set to 0 for auto length
    user_running_step_length: float
    # User defined walking step length set to 0 for auto length
    user_walking_step_length: float
    depth_setting: DisplayMeasure
    dive_count: int



class HrmProfileMesg(FitMesg, total=False):
    message_index: MessageIndex
    enabled: bool
    hrm_ant_id: int
    log_hrv: bool
    hrm_ant_id_trans_type: int



class SdmProfileMesg(FitMesg, total=False):
    message_index: MessageIndex
    enabled: bool
    sdm_ant_id: int
    sdm_cal_factor: float
    odometer: float
    # Use footpod for speed source instead of GPS
    speed_source: bool
    sdm_ant_id_trans_type: int
    # Rollover counter that can be used to extend the odometer
    odometer_rollover: int



class BikeProfileMesg(FitMesg, total=False):
    message_index: MessageIndex
    name: StringValue
    sport: Sport
    sub_sport: SubSport
    odometer: float
    bike_spd_ant_id: int
    bike_cad_ant_id: int
    bike_spdcad_ant_id: int
    bike_power_ant_id: int
    custom_wheelsize: float
    auto_wheelsize: float
    bike_weight: float
    power_cal_factor: float
    auto_wheel_cal: bool
    auto_power_zero: bool
    id: int
    spd_enabled: bool
    cad_enabled: bool
    spdcad_enabled: bool
    power_enabled: bool
    crank_length: float
    enabled: bool
    bike_spd_ant_id_trans_type: int
    bike_cad_ant_id_trans_type: int
    bike_spdcad_ant_id_trans_type: int
    bike_power_ant_id_trans_type: int
    # Rollover counter that can be used to extend the odometer
    odometer_rollover: int
    # Number of front gears
    front_gear_num: int
    # Number of teeth on each gear 0 is innermost
    front_gear: Union[int, List[Optional[int]]]
    # Number of rear gears
    rear_gear_num: int
    # Number of teeth on each gear 0 is innermost
    rear_gear: Union[int, List[Optional[int]]]
    shimano_di2_enabled: bool



class ConnectivityMesg(FitMesg, total=False):
    # Use Bluetooth for connectivity features
    bluetooth_enabled: bool
    # Use Bluetooth Low Energy for connectivity features
    bluetooth_le_enabled: bool
    # Use ANT for connectivity features
    ant_enabled: bool
    name: StringValue
    live_tracking_enabled: bool
    weather_conditions_enabled: bool
    weather_alerts_enabled: bool
    auto_activity_upload_enabled: bool
    course_download_enabled: bool
    workout_download_enabled: bool
    gps_ephemeris_download_enabled: bool
    incident_detection_enabled: bool
    grouptrack_enabled: bool



class WatchfaceSettingsMesg(FitMesg, total=False):
    message_index: MessageIndex
    mode: WatchfaceMode
    layout: int
    digital_layout: DigitalWatchfaceLayout
    analog_layout: AnalogWatchfaceLayout



class OhrSettingsMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    enabled: Switch



class TimeInZoneMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    reference_mesg: MesgNum
    reference_index: MessageIndex
    time_in_hr_zone: Union[float, List[Optional[float]]]
    time_in_speed_zone: Union[float, List[Optional[float]]]
    time_in_cadence_zone: Union[float, List[Optional[float]]]
    time_in_power_zone: Union[float, List[Optional[float]]]
    hr_zone_high_boundary: Union[int, List[Optional[int]]]
    speed_zone_high_boundary: Union[float, List[Optional[float]]]
    cadence_zone_high_bondary: Union[int, List[Optional[int]]]
    power_zone_high_boundary: Union[int, List[Optional[int]]]
    hr_calc_type: HrZoneCalc
    max_heart_rate: int
    resting_heart_rate: int
    threshold_heart_rate: int
    pwr_calc_type: PwrZoneCalc
    functional_threshold_power: int



class ZonesTargetMesg(FitMesg, total=False):
    max_heart_rate: int
    threshold_heart_rate: int
    functional_threshold_power: int
    hr_calc_type: HrZoneCalc
    pwr_calc_type: PwrZoneCalc



class SportMesg(FitMesg, total=False):
    sport: Sport
    sub_sport: SubSport
    name: StringValue



class HrZoneMesg(FitMesg, total=False):
    message_index: MessageIndex
    high_bpm: int
    name: StringValue



class SpeedZoneMesg(FitMesg, total=False):
    message_index: MessageIndex
    high_value: float
    name: StringValue



class CadenceZoneMesg(FitMesg, total=False):
    message_index: MessageIndex
    high_value: int
    name: StringValue



class PowerZoneMesg(FitMesg, total=False):
    message_index: MessageIndex
    high_value: int
    name: StringValue



class MetZoneMesg(FitMesg, total=False):
    message_index: MessageIndex
    high_bpm: int
    calories: float
    fat_calories: float



class TrainingSettingsMesg(FitMesg, total=False):
    target_distance: float
    target_speed: float
    target_time: int
    # A more precise target speed field
    precise_target_speed: float



class DiveSettingsMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    message_index: MessageIndex
    name: StringValue
    model: TissueModelType
    gf_low: int
    gf_high: int
    water_type: WaterType
    # Fresh water is usually 1000; salt water is usually 1025
    water_density: float
    # Typically 1.40
    po2_warn: float
    # Typically 1.60
    po2_critical: float
    po2_deco: float
    safety_stop_enabled: bool
    bottom_depth: float
    bottom_time: int
    apnea_countdown_enabled: bool
    apnea_countdown_time: int
    backlight_mode: DiveBacklightMode
    backlight_brightness: int
    backlight_timeout: BacklightTimeout
    # Time between surfacing and ending the activity
    repeat_dive_interval: int
    # Time at safety stop (if enabled)
    safety_stop_time: int
    heart_rate_source_type: SourceType
    heart_rate_source: int
    heart_rate_antplus_device_type: AntplusDeviceType
    heart_rate_local_device_type: LocalDeviceType
    # Index of travel dive_gas message
    travel_gas: MessageIndex
    # If low PO2 should be switched to automatically
    ccr_low_setpoint_switch_mode: CcrSetpointSwitchMode
    # Target PO2 when using low setpoint
    ccr_low_setpoint: float
    # Depth to switch to low setpoint in automatic mode
    ccr_low_setpoint_depth: float
    # If high PO2 should be switched to automatically
    ccr_high_setpoint_switch_mode: CcrSetpointSwitchMode
    # Target PO2 when using high setpoint
    ccr_high_setpoint: float
    # Depth to switch to high setpoint in automatic mode
    ccr_high_setpoint_depth: float
    # Type of gas consumption rate to display. Some values are only valid if tank volume is known.
    gas_consumption_display: GasConsumptionRateType
    # Indicates whether the up key is enabled during dives
    up_key_enabled: bool
    # Sounds and vibration enabled or disabled in-dive
    dive_sounds: Tone
    # Usually 1.0/1.5/2.0 representing 3/4.5/6m or 10/15/20ft
    last_stop_multiple: float
    # Indicates which guidelines to use for no-fly surface interval.
    no_fly_time_mode: NoFlyTimeMode



class DiveAlarmMesg(FitMesg, total=False):
    # Index of the alarm
    message_index: MessageIndex
    # Depth setting (m) for depth type alarms
    depth: float
    # Time setting (s) for time type alarms
    time: int
    # Enablement flag
    enabled: bool
    # Alarm type setting
    alarm_type: DiveAlarmType
    # Tone and Vibe setting for the alarm
    sound: Tone
    # Dive types the alarm will trigger on
    dive_types: Union[SubSport, List[Optional[SubSport]]]
    # Alarm ID
    id: int
    # Show a visible pop-up for this alarm
    popup_enabled: bool
    # Trigger the alarm on descent
    trigger_on_descent: bool
    # Trigger the alarm on ascent
    trigger_on_ascent: bool
    # Repeat alarm each time threshold is crossed?
    repeating: bool
    # Ascent/descent rate (mps) setting for speed type alarms
    speed: float



class DiveApneaAlarmMesg(FitMesg, total=False):
    # Index of the alarm
    message_index: MessageIndex
    # Depth setting (m) for depth type alarms
    depth: float
    # Time setting (s) for time type alarms
    time: int
    # Enablement flag
    enabled: bool
    # Alarm type setting
    alarm_type: DiveAlarmType
    # Tone and Vibe setting for the alarm.
    sound: Tone
    # Dive types the alarm will trigger on
    dive_types: Union[SubSport, List[Optional[SubSport]]]
    # Alarm ID
    id: int
    # Show a visible pop-up for this alarm
    popup_enabled: bool
    # Trigger the alarm on descent
    trigger_on_descent: bool
    # Trigger the alarm on ascent
    trigger_on_ascent: bool
    # Repeat alarm each time threshold is crossed?
    repeating: bool
    # Ascent/descent rate (mps) setting for speed type alarms
    speed: float



class DiveGasMesg(FitMesg, total=False):
    message_index: MessageIndex
    helium_content: int
    oxygen_content: int
    status: DiveGasStatus
    mode: DiveGasMode



class GoalMesg(FitMesg, total=False):
    message_index: MessageIndex
    sport: Sport
    sub_sport: SubSport
    start_date: Union[int, datetime]
    end_date: Union[int, datetime]
    type: Goal
    value: int
    repeat: bool
    target_value: int
    recurrence: GoalRecurrence
    recurrence_value: int
    enabled: bool
    source: GoalSource



class ActivityMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Exclude pauses
    total_timer_time: float
    num_sessions: int
    type: Activity
    event: Event
    event_type: EventType
    # timestamp epoch expressed in local time, used to convert activity timestamps to local time
    local_timestamp: Union[int, datetime]
    event_group: int



class SessionMesg(FitMesg, total=False):
    # Selected bit is set for the current session.
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    # session
    event: Event
    # stop
    event_type: EventType
    start_time: Union[int, datetime]
    start_position_lat: int
    start_position_long: int
    sport: Sport
    sub_sport: SubSport
    # Time (includes pauses)
    total_elapsed_time: float
    # Timer Time (excludes pauses)
    total_timer_time: float
    total_distance: float
    total_cycles: int
    total_reps: int
    total_strides: int
    total_strokes: int
    # total number of pushes in a session
    total_pushes: int
    total_calories: int
    total_fat_calories: int
    # total_distance / total_timer_time
    avg_speed: float
    max_speed: float
    # average heart rate (excludes pause time)
    avg_heart_rate: int
    max_heart_rate: int
    # total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
    avg_cadence: int
    avg_running_cadence: int
    max_cadence: int
    max_running_cadence: int
    # total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
    avg_power: int
    max_power: int
    total_ascent: int
    total_descent: int
    total_training_effect: float
    first_lap_index: int
    num_laps: int
    event_group: int
    trigger: SessionTrigger
    # North east corner latitude
    nec_lat: int
    # North east corner longitude
    nec_long: int
    # South west corner latitude
    swc_lat: int
    # South west corner longitude
    swc_long: int
    # # of lengths of swim pool
    num_lengths: int
    normalized_power: int
    training_stress_score: float
    intensity_factor: float
    left_right_balance: LeftRightBalance100
    end_position_lat: int
    end_position_long: int
    avg_stroke_count: float
    avg_stroke_distance: float
    swim_stroke: SwimStroke
    pool_length: float
    threshold_power: int
    pool_length_unit: DisplayMeasure
    # # of active lengths of swim pool
    num_active_lengths: int
    total_work: int
    avg_altitude: float
    max_altitude: float
    gps_accuracy: int
    avg_grade: float
    avg_pos_grade: float
    avg_neg_grade: float
    max_pos_grade: float
    max_neg_grade: float
    avg_temperature: int
    max_temperature: int
    total_moving_time: float
    avg_pos_vertical_speed: float
    avg_neg_vertical_speed: float
    max_pos_vertical_speed: float
    max_neg_vertical_speed: float
    min_heart_rate: int
    time_in_hr_zone: Union[float, List[Optional[float]]]
    time_in_speed_zone: Union[float, List[Optional[float]]]
    time_in_cadence_zone: Union[float, List[Optional[float]]]
    time_in_power_zone: Union[float, List[Optional[float]]]
    avg_lap_time: float
    best_lap_index: int
    min_altitude: float
    active_time: float
    player_score: int
    opponent_score: int
    opponent_name: StringValue
    # stroke_type enum used as the index
    stroke_count: Union[int, List[Optional[int]]]
    # zone number used as the index
    zone_count: Union[int, List[Optional[int]]]
    max_ball_speed: float
    avg_ball_speed: float
    avg_vertical_oscillation: float
    avg_stance_time_percent: float
    avg_stance_time: float
    # fractional part of the avg_cadence
    avg_fractional_cadence: float
    # fractional part of the max_cadence
    max_fractional_cadence: float
    # fractional part of the total_cycles
    total_fractional_cycles: float
    # Avg saturated and unsaturated hemoglobin
    avg_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Min saturated and unsaturated hemoglobin
    min_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Max saturated and unsaturated hemoglobin
    max_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Avg percentage of hemoglobin saturated with oxygen
    avg_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    # Min percentage of hemoglobin saturated with oxygen
    min_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    # Max percentage of hemoglobin saturated with oxygen
    max_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    avg_left_torque_effectiveness: float
    avg_right_torque_effectiveness: float
    avg_left_pedal_smoothness: float
    avg_right_pedal_smoothness: float
    avg_combined_pedal_smoothness: float
    # Sport name from associated sport mesg
    sport_profile_name: StringValue
    sport_index: int
    # Total time spend in the standing position
    time_standing: float
    # Number of transitions to the standing state
    stand_count: int
    # Average platform center offset Left
    avg_left_pco: int
    # Average platform center offset Right
    avg_right_pco: int
    # Average left power phase angles. Indexes defined by power_phase_type.
    avg_left_power_phase: Union[float, List[Optional[float]]]
    # Average left power phase peak angles. Data value indexes defined by power_phase_type.
    avg_left_power_phase_peak: Union[float, List[Optional[float]]]
    # Average right power phase angles. Data value indexes defined by power_phase_type.
    avg_right_power_phase: Union[float, List[Optional[float]]]
    # Average right power phase peak angles data value indexes defined by power_phase_type.
    avg_right_power_phase_peak: Union[float, List[Optional[float]]]
    # Average power by position. Data value indexes defined by rider_position_type.
    avg_power_position: Union[int, List[Optional[int]]]
    # Maximum power by position. Data value indexes defined by rider_position_type.
    max_power_position: Union[int, List[Optional[int]]]
    # Average cadence by position. Data value indexes defined by rider_position_type.
    avg_cadence_position: Union[int, List[Optional[int]]]
    # Maximum cadence by position. Data value indexes defined by rider_position_type.
    max_cadence_position: Union[int, List[Optional[int]]]
    # total_distance / total_timer_time
    enhanced_avg_speed: float
    enhanced_max_speed: float
    enhanced_avg_altitude: float
    enhanced_min_altitude: float
    enhanced_max_altitude: float
    # lev average motor power during session
    avg_lev_motor_power: int
    # lev maximum motor power during session
    max_lev_motor_power: int
    # lev battery consumption during session
    lev_battery_consumption: float
    avg_vertical_ratio: float
    avg_stance_time_balance: float
    avg_step_length: float
    total_anaerobic_training_effect: float
    avg_vam: float
    # 0 if above water
    avg_depth: float
    # 0 if above water
    max_depth: float
    # Time since end of last dive
    surface_interval: int
    start_cns: int
    end_cns: int
    start_n2: int
    end_n2: int
    avg_respiration_rate: int
    max_respiration_rate: int
    min_respiration_rate: int
    min_temperature: int
    o2_toxicity: int
    dive_number: int
    training_load_peak: float
    enhanced_avg_respiration_rate: float
    enhanced_max_respiration_rate: float
    enhanced_min_respiration_rate: float
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    total_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    total_flow: float
    jump_count: int
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    avg_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    avg_flow: float
    # A 0-100 scale representing how a user felt while performing a workout. Low values are considered feeling bad, while high values are good.
    workout_feel: int
    # Common Borg CR10 / 0-10 RPE scale, multiplied 10x.. Aggregate score for all workouts in a single session.
    workout_rpe: int
    # Average SPO2 for the monitoring session
    avg_spo2: int
    # Average stress for the monitoring session
    avg_stress: int
    metabolic_calories: int
    # Standard deviation of R-R interval (SDRR) - Heart rate variability measure most useful for wellness users.
    sdrr_hrv: int
    # Root mean square successive difference (RMSSD) - Heart rate variability measure most useful for athletes
    rmssd_hrv: int
    # fractional part of total_ascent
    total_fractional_ascent: float
    # fractional part of total_descent
    total_fractional_descent: float
    avg_core_temperature: float
    min_core_temperature: float
    max_core_temperature: float



class LapMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    event: Event
    event_type: EventType
    start_time: Union[int, datetime]
    start_position_lat: int
    start_position_long: int
    end_position_lat: int
    end_position_long: int
    # Time (includes pauses)
    total_elapsed_time: float
    # Timer Time (excludes pauses)
    total_timer_time: float
    total_distance: float
    total_cycles: int
    total_strides: int
    total_strokes: int
    total_calories: int
    # If New Leaf
    total_fat_calories: int
    avg_speed: float
    max_speed: float
    avg_heart_rate: int
    max_heart_rate: int
    # total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
    avg_cadence: int
    avg_running_cadence: int
    max_cadence: int
    max_running_cadence: int
    # total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
    avg_power: int
    max_power: int
    total_ascent: int
    total_descent: int
    intensity: Intensity
    lap_trigger: LapTrigger
    sport: Sport
    event_group: int
    # # of lengths of swim pool
    num_lengths: int
    normalized_power: int
    left_right_balance: LeftRightBalance100
    first_length_index: int
    avg_stroke_distance: float
    swim_stroke: SwimStroke
    sub_sport: SubSport
    # # of active lengths of swim pool
    num_active_lengths: int
    total_work: int
    avg_altitude: float
    max_altitude: float
    gps_accuracy: int
    avg_grade: float
    avg_pos_grade: float
    avg_neg_grade: float
    max_pos_grade: float
    max_neg_grade: float
    avg_temperature: int
    max_temperature: int
    total_moving_time: float
    avg_pos_vertical_speed: float
    avg_neg_vertical_speed: float
    max_pos_vertical_speed: float
    max_neg_vertical_speed: float
    time_in_hr_zone: Union[float, List[Optional[float]]]
    time_in_speed_zone: Union[float, List[Optional[float]]]
    time_in_cadence_zone: Union[float, List[Optional[float]]]
    time_in_power_zone: Union[float, List[Optional[float]]]
    repetition_num: int
    min_altitude: float
    min_heart_rate: int
    active_time: float
    wkt_step_index: MessageIndex
    opponent_score: int
    # stroke_type enum used as the index
    stroke_count: Union[int, List[Optional[int]]]
    # zone number used as the index
    zone_count: Union[int, List[Optional[int]]]
    avg_vertical_oscillation: float
    avg_stance_time_percent: float
    avg_stance_time: float
    # fractional part of the avg_cadence
    avg_fractional_cadence: float
    # fractional part of the max_cadence
    max_fractional_cadence: float
    # fractional part of the total_cycles
    total_fractional_cycles: float
    player_score: int
    # Avg saturated and unsaturated hemoglobin
    avg_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Min saturated and unsaturated hemoglobin
    min_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Max saturated and unsaturated hemoglobin
    max_total_hemoglobin_conc: Union[float, List[Optional[float]]]
    # Avg percentage of hemoglobin saturated with oxygen
    avg_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    # Min percentage of hemoglobin saturated with oxygen
    min_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    # Max percentage of hemoglobin saturated with oxygen
    max_saturated_hemoglobin_percent: Union[float, List[Optional[float]]]
    avg_left_torque_effectiveness: float
    avg_right_torque_effectiveness: float
    avg_left_pedal_smoothness: float
    avg_right_pedal_smoothness: float
    avg_combined_pedal_smoothness: float
    # Total time spent in the standing position
    time_standing: float
    # Number of transitions to the standing state
    stand_count: int
    # Average left platform center offset
    avg_left_pco: int
    # Average right platform center offset
    avg_right_pco: int
    # Average left power phase angles. Data value indexes defined by power_phase_type.
    avg_left_power_phase: Union[float, List[Optional[float]]]
    # Average left power phase peak angles. Data value indexes defined by power_phase_type.
    avg_left_power_phase_peak: Union[float, List[Optional[float]]]
    # Average right power phase angles. Data value indexes defined by power_phase_type.
    avg_right_power_phase: Union[float, List[Optional[float]]]
    # Average right power phase peak angles. Data value indexes defined by power_phase_type.
    avg_right_power_phase_peak: Union[float, List[Optional[float]]]
    # Average power by position. Data value indexes defined by rider_position_type.
    avg_power_position: Union[int, List[Optional[int]]]
    # Maximum power by position. Data value indexes defined by rider_position_type.
    max_power_position: Union[int, List[Optional[int]]]
    # Average cadence by position. Data value indexes defined by rider_position_type.
    avg_cadence_position: Union[int, List[Optional[int]]]
    # Maximum cadence by position. Data value indexes defined by rider_position_type.
    max_cadence_position: Union[int, List[Optional[int]]]
    enhanced_avg_speed: float
    enhanced_max_speed: float
    enhanced_avg_altitude: float
    enhanced_min_altitude: float
    enhanced_max_altitude: float
    # lev average motor power during lap
    avg_lev_motor_power: int
    # lev maximum motor power during lap
    max_lev_motor_power: int
    # lev battery consumption during lap
    lev_battery_consumption: float
    avg_vertical_ratio: float
    avg_stance_time_balance: float
    avg_step_length: float
    avg_vam: float
    # 0 if above water
    avg_depth: float
    # 0 if above water
    max_depth: float
    min_temperature: int
    enhanced_avg_respiration_rate: float
    enhanced_max_respiration_rate: float
    avg_respiration_rate: int
    max_respiration_rate: int
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    total_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    total_flow: float
    jump_count: int
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    avg_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    avg_flow: float
    # fractional part of total_ascent
    total_fractional_ascent: float
    # fractional part of total_descent
    total_fractional_descent: float
    avg_core_temperature: float
    min_core_temperature: float
    max_core_temperature: float



class LengthMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    event: Event
    event_type: EventType
    start_time: Union[int, datetime]
    total_elapsed_time: float
    total_timer_time: float
    total_strokes: int
    avg_speed: float
    swim_stroke: SwimStroke
    avg_swimming_cadence: int
    event_group: int
    total_calories: int
    length_type: LengthType
    player_score: int
    opponent_score: int
    # stroke_type enum used as the index
    stroke_count: Union[int, List[Optional[int]]]
    # zone number used as the index
    zone_count: Union[int, List[Optional[int]]]
    enhanced_avg_respiration_rate: float
    enhanced_max_respiration_rate: float
    avg_respiration_rate: int
    max_respiration_rate: int



class RecordMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    position_lat: int
    position_long: int
    altitude: float
    heart_rate: int
    cadence: int
    distance: float
    speed: float
    power: int
    compressed_speed_distance: Union[int, List[Optional[int]]]
    grade: float
    # Relative. 0 is none 254 is Max.
    resistance: int
    time_from_course: float
    cycle_length: float
    temperature: int
    # Speed at 1s intervals. Timestamp field indicates time of last array element.
    speed_1s: Union[float, List[Optional[float]]]
    cycles: int
    total_cycles: int
    compressed_accumulated_power: int
    accumulated_power: int
    left_right_balance: LeftRightBalance
    gps_accuracy: int
    vertical_speed: float
    calories: int
    vertical_oscillation: float
    stance_time_percent: float
    stance_time: float
    activity_type: ActivityType
    left_torque_effectiveness: float
    right_torque_effectiveness: float
    left_pedal_smoothness: float
    right_pedal_smoothness: float
    combined_pedal_smoothness: float
    time128: float
    stroke_type: StrokeType
    zone: int
    ball_speed: float
    # Log cadence and fractional cadence for backwards compatability
    cadence256: float
    fractional_cadence: float
    # Total saturated and unsaturated hemoglobin
    total_hemoglobin_conc: float
    # Min saturated and unsaturated hemoglobin
    total_hemoglobin_conc_min: float
    # Max saturated and unsaturated hemoglobin
    total_hemoglobin_conc_max: float
    # Percentage of hemoglobin saturated with oxygen
    saturated_hemoglobin_percent: float
    # Min percentage of hemoglobin saturated with oxygen
    saturated_hemoglobin_percent_min: float
    # Max percentage of hemoglobin saturated with oxygen
    saturated_hemoglobin_percent_max: float
    device_index: DeviceIndex
    # Left platform center offset
    left_pco: int
    # Right platform center offset
    right_pco: int
    # Left power phase angles. Data value indexes defined by power_phase_type.
    left_power_phase: Union[float, List[Optional[float]]]
    # Left power phase peak angles. Data value indexes defined by power_phase_type.
    left_power_phase_peak: Union[float, List[Optional[float]]]
    # Right power phase angles. Data value indexes defined by power_phase_type.
    right_power_phase: Union[float, List[Optional[float]]]
    # Right power phase peak angles. Data value indexes defined by power_phase_type.
    right_power_phase_peak: Union[float, List[Optional[float]]]
    enhanced_speed: float
    enhanced_altitude: float
    # lev battery state of charge
    battery_soc: float
    # lev motor power
    motor_power: int
    vertical_ratio: float
    stance_time_balance: float
    step_length: float
    # Supports larger cycle sizes needed for paddlesports. Max cycle size: 655.35
    cycle_length16: float
    # Includes atmospheric pressure
    absolute_pressure: int
    # 0 if above water
    depth: float
    # 0 if above water
    next_stop_depth: float
    next_stop_time: int
    time_to_surface: int
    ndl_time: int
    cns_load: int
    n2_load: int
    respiration_rate: int
    enhanced_respiration_rate: float
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    flow: float
    # Current Stress value
    current_stress: float
    ebike_travel_range: int
    ebike_battery_level: int
    ebike_assist_mode: int
    ebike_assist_level_percent: int
    air_time_remaining: int
    # Pressure-based surface air consumption
    pressure_sac: float
    # Volumetric surface air consumption
    volume_sac: float
    # Respiratory minute volume
    rmv: float
    ascent_rate: float
    # Current partial pressure of oxygen
    po2: float
    core_temperature: float



class EventMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    event: Event
    event_type: EventType
    data16: int
    data: int
    timer_trigger: TimerTrigger
    course_point_index: MessageIndex
    battery_level: float
    virtual_partner_speed: float
    hr_high_alert: int
    hr_low_alert: int
    speed_high_alert: float
    speed_low_alert: float
    cad_high_alert: int
    cad_low_alert: int
    power_high_alert: int
    power_low_alert: int
    time_duration_alert: float
    distance_duration_alert: float
    calorie_duration_alert: int
    fitness_equipment_state: FitnessEquipmentState
    sport_point: int
    gear_change_data: int
    # Indicates the rider position value.
    rider_position: RiderPositionType
    comm_timeout: CommTimeoutType
    dive_alert: DiveAlert
    auto_activity_detect_duration: int
    # The first byte is the radar_threat_level_max, the second byte is the radar_threat_count, third bytes is the average approach speed, and the 4th byte is the max approach speed
    radar_threat_alert: int
    event_group: int
    # Do not populate directly. Autogenerated by decoder for sport_point subfield components
    score: int
    # Do not populate directly. Autogenerated by decoder for sport_point subfield components
    opponent_score: int
    # Do not populate directly. Autogenerated by decoder for gear_change subfield components. Front gear number. 1 is innermost.
    front_gear_num: int
    # Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of front teeth.
    front_gear: int
    # Do not populate directly. Autogenerated by decoder for gear_change subfield components. Rear gear number. 1 is innermost.
    rear_gear_num: int
    # Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of rear teeth.
    rear_gear: int
    device_index: DeviceIndex
    # Activity Type associated with an auto_activity_detect event
    activity_type: ActivityType
    # Timestamp of when the event started
    start_timestamp: Union[int, datetime]
    # Auto Activity Detect Start Timestamp.
    auto_activity_detect_start_timestamp: Union[int, datetime]
    # Do not populate directly. Autogenerated by decoder for threat_alert subfield components.
    radar_threat_level_max: RadarThreatLevelType
    # Do not populate directly. Autogenerated by decoder for threat_alert subfield components.
    radar_threat_count: int
    # Do not populate directly. Autogenerated by decoder for radar_threat_alert subfield components
    radar_threat_avg_approach_speed: float
    # Do not populate directly. Autogenerated by decoder for radar_threat_alert subfield components
    radar_threat_max_approach_speed: float



class DeviceInfoMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    device_index: DeviceIndex
    device_type: int
    ble_device_type: BleDeviceType
    antplus_device_type: AntplusDeviceType
    ant_device_type: int
    local_device_type: LocalDeviceType
    manufacturer: Manufacturer
    serial_number: int
    product: int
    favero_product: FaveroProduct
    garmin_product: GarminProduct
    software_version: float
    hardware_version: int
    # Reset by new battery or charge.
    cum_operating_time: int
    battery_voltage: float
    battery_status: BatteryStatus
    # Indicates the location of the sensor
    sensor_position: BodyLocation
    # Used to describe the sensor or location
    descriptor: StringValue
    ant_transmission_type: int
    ant_device_number: int
    ant_network: AntNetwork
    source_type: SourceType
    # Optional free form string to indicate the devices name or model
    product_name: StringValue
    battery_level: int



class DeviceAuxBatteryInfoMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    device_index: DeviceIndex
    battery_voltage: float
    battery_status: BatteryStatus
    battery_identifier: int



# Corresponds to file_id of workout or course.
class TrainingFileMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    type: File
    manufacturer: Manufacturer
    product: int
    favero_product: FaveroProduct
    garmin_product: GarminProduct
    serial_number: int
    time_created: Union[int, datetime]



class WeatherConditionsMesg(FitMesg, total=False):
    # time of update for current conditions, else forecast time
    timestamp: Union[int, datetime]
    # Current or forecast
    weather_report: WeatherReport
    temperature: int
    # Corresponds to GSC Response weatherIcon field
    condition: WeatherStatus
    wind_direction: int
    wind_speed: float
    # range 0-100
    precipitation_probability: int
    # Heat Index if GCS heatIdx above or equal to 90F or wind chill if GCS windChill below or equal to 32F
    temperature_feels_like: int
    relative_humidity: int
    # string corresponding to GCS response location string
    location: StringValue
    observed_at_time: Union[int, datetime]
    observed_location_lat: int
    observed_location_long: int
    day_of_week: DayOfWeek
    high_temperature: int
    low_temperature: int



class WeatherAlertMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Unique identifier from GCS report ID string, length is 12
    report_id: StringValue
    # Time alert was issued
    issue_time: Union[int, datetime]
    # Time alert expires
    expire_time: Union[int, datetime]
    # Warning, Watch, Advisory, Statement
    severity: WeatherSeverity
    # Tornado, Severe Thunderstorm, etc.
    type: WeatherSevereType



class GpsMetadataMesg(FitMesg, total=False):
    # Whole second part of the timestamp.
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    position_lat: int
    position_long: int
    enhanced_altitude: float
    enhanced_speed: float
    heading: float
    # Used to correlate UTC to system time if the timestamp of the message is in system time. This UTC time is derived from the GPS data.
    utc_timestamp: Union[int, datetime]
    # velocity[0] is lon velocity. Velocity[1] is lat velocity. Velocity[2] is altitude velocity.
    velocity: Union[float, List[Optional[float]]]



class CameraEventMesg(FitMesg, total=False):
    # Whole second part of the timestamp.
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    camera_event_type: CameraEventType
    camera_file_uuid: StringValue
    camera_orientation: CameraOrientationType



class GyroscopeDataMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    # Each time in the array describes the time at which the gyro sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in gyro_x and gyro_y and gyro_z
    sample_time_offset: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    gyro_x: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    gyro_y: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    gyro_z: Union[int, List[Optional[int]]]
    # Calibrated gyro reading
    calibrated_gyro_x: Union[float, List[Optional[float]]]
    # Calibrated gyro reading
    calibrated_gyro_y: Union[float, List[Optional[float]]]
    # Calibrated gyro reading
    calibrated_gyro_z: Union[float, List[Optional[float]]]



class AccelerometerDataMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    # Each time in the array describes the time at which the accelerometer sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in accel_x and accel_y and accel_z
    sample_time_offset: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    accel_x: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    accel_y: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    accel_z: Union[int, List[Optional[int]]]
    # Calibrated accel reading
    calibrated_accel_x: Union[float, List[Optional[float]]]
    # Calibrated accel reading
    calibrated_accel_y: Union[float, List[Optional[float]]]
    # Calibrated accel reading
    calibrated_accel_z: Union[float, List[Optional[float]]]
    # Calibrated accel reading
    compressed_calibrated_accel_x: Union[int, List[Optional[int]]]
    # Calibrated accel reading
    compressed_calibrated_accel_y: Union[int, List[Optional[int]]]
    # Calibrated accel reading
    compressed_calibrated_accel_z: Union[int, List[Optional[int]]]



class MagnetometerDataMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    # Each time in the array describes the time at which the compass sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in cmps_x and cmps_y and cmps_z
    sample_time_offset: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    mag_x: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    mag_y: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
    mag_z: Union[int, List[Optional[int]]]
    # Calibrated Magnetometer reading
    calibrated_mag_x: Union[float, List[Optional[float]]]
    # Calibrated Magnetometer reading
    calibrated_mag_y: Union[float, List[Optional[float]]]
    # Calibrated Magnetometer reading
    calibrated_mag_z: Union[float, List[Optional[float]]]



class BarometerDataMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    # Each time in the array describes the time at which the barometer sample with the corrosponding index was taken. The samples may span across seconds. Array size must match the number of samples in baro_cal
    sample_time_offset: Union[int, List[Optional[int]]]
    # These are the raw ADC reading. The samples may span across seconds. A conversion will need to be done on this data once read.
    baro_pres: Union[int, List[Optional[int]]]



class ThreeDSensorCalibrationMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Indicates which sensor the calibration is for
    sensor_type: SensorType
    # Calibration factor used to convert from raw ADC value to degrees, g, etc.
    calibration_factor: int
    # Accelerometer calibration factor
    accel_cal_factor: int
    # Gyro calibration factor
    gyro_cal_factor: int
    # Calibration factor divisor
    calibration_divisor: int
    # Level shift value used to shift the ADC value back into range
    level_shift: int
    # Internal calibration factors, one for each: xy, yx, zx
    offset_cal: Union[int, List[Optional[int]]]
    # 3 x 3 rotation matrix (row major)
    orientation_matrix: Union[float, List[Optional[float]]]



class OneDSensorCalibrationMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Indicates which sensor the calibration is for
    sensor_type: SensorType
    # Calibration factor used to convert from raw ADC value to degrees, g, etc.
    calibration_factor: int
    # Barometer calibration factor
    baro_cal_factor: int
    # Calibration factor divisor
    calibration_divisor: int
    # Level shift value used to shift the ADC value back into range
    level_shift: int
    # Internal Calibration factor
    offset_cal: int



class VideoFrameMesg(FitMesg, total=False):
    # Whole second part of the timestamp
    timestamp: Union[int, datetime]
    # Millisecond part of the timestamp.
    timestamp_ms: int
    # Number of the frame that the timestamp and timestamp_ms correlate to
    frame_number: int



class ObdiiDataMesg(FitMesg, total=False):
    # Timestamp message was output
    timestamp: Union[int, datetime]
    # Fractional part of timestamp, added to timestamp
    timestamp_ms: int
    # Offset of PID reading [i] from start_timestamp+start_timestamp_ms. Readings may span accross seconds.
    time_offset: Union[int, List[Optional[int]]]
    # Parameter ID
    pid: int
    # Raw parameter data
    raw_data: Union[int, List[Optional[int]]]
    # Optional, data size of PID[i]. If not specified refer to SAE J1979.
    pid_data_size: Union[int, List[Optional[int]]]
    # System time associated with sample expressed in ms, can be used instead of time_offset. There will be a system_time value for each raw_data element. For multibyte pids the system_time is repeated.
    system_time: Union[int, List[Optional[int]]]
    # Timestamp of first sample recorded in the message. Used with time_offset to generate time of each sample
    start_timestamp: Union[int, datetime]
    # Fractional part of start_timestamp
    start_timestamp_ms: int



class NmeaSentenceMesg(FitMesg, total=False):
    # Timestamp message was output
    timestamp: Union[int, datetime]
    # Fractional part of timestamp, added to timestamp
    timestamp_ms: int
    # NMEA sentence
    sentence: StringValue



class AviationAttitudeMesg(FitMesg, total=False):
    # Timestamp message was output
    timestamp: Union[int, datetime]
    # Fractional part of timestamp, added to timestamp
    timestamp_ms: int
    # System time associated with sample expressed in ms.
    system_time: Union[int, List[Optional[int]]]
    # Range -PI/2 to +PI/2
    pitch: Union[float, List[Optional[float]]]
    # Range -PI to +PI
    roll: Union[float, List[Optional[float]]]
    # Range -78.4 to +78.4 (-8 Gs to 8 Gs)
    accel_lateral: Union[float, List[Optional[float]]]
    # Range -78.4 to +78.4 (-8 Gs to 8 Gs)
    accel_normal: Union[float, List[Optional[float]]]
    # Range -8.727 to +8.727 (-500 degs/sec to +500 degs/sec)
    turn_rate: Union[float, List[Optional[float]]]
    stage: Union[AttitudeStage, List[Optional[AttitudeStage]]]
    # The percent complete of the current attitude stage. Set to 0 for attitude stages 0, 1 and 2 and to 100 for attitude stage 3 by AHRS modules that do not support it. Range - 100
    attitude_stage_complete: Union[int, List[Optional[int]]]
    # Track Angle/Heading Range 0 - 2pi
    track: Union[float, List[Optional[float]]]
    validity: Union[AttitudeValidity, List[Optional[AttitudeValidity]]]



class VideoMesg(FitMesg, total=False):
    url: StringValue
    hosting_provider: StringValue
    # Playback time of video
    duration: int



class VideoTitleMesg(FitMesg, total=False):
    # Long titles will be split into multiple parts
    message_index: MessageIndex
    # Total number of title parts
    message_count: int
    text: StringValue



class VideoDescriptionMesg(FitMesg, total=False):
    # Long descriptions will be split into multiple parts
    message_index: MessageIndex
    # Total number of description parts
    message_count: int
    text: StringValue



class VideoClipMesg(FitMesg, total=False):
    clip_number: int
    start_timestamp: Union[int, datetime]
    start_timestamp_ms: int
    end_timestamp: Union[int, datetime]
    end_timestamp_ms: int
    # Start of clip in video time
    clip_start: int
    # End of clip in video time
    clip_end: int



class SetMesg(FitMesg, total=False):
    # Timestamp of the set
    timestamp: Union[int, datetime]
    duration: float
    # # of repitions of the movement
    repetitions: int
    # Amount of weight applied for the set
    weight: float
    set_type: SetType
    # Start time of the set
    start_time: Union[int, datetime]
    category: Union[ExerciseCategory, List[Optional[ExerciseCategory]]]
    # Based on the associated category, see [category]_exercise_names
    category_subtype: Union[int, List[Optional[int]]]
    weight_display_unit: FitBaseUnit
    message_index: MessageIndex
    wkt_step_index: MessageIndex



class JumpMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    distance: float
    height: float
    rotations: int
    hang_time: float
    # A score for a jump calculated based on hang time, rotations, and distance.
    score: float
    position_lat: int
    position_long: int
    speed: float
    enhanced_speed: float



class SplitMesg(FitMesg, total=False):
    message_index: MessageIndex
    split_type: SplitType
    total_elapsed_time: float
    total_timer_time: float
    total_distance: float
    avg_speed: float
    start_time: Union[int, datetime]
    total_ascent: int
    total_descent: int
    start_position_lat: int
    start_position_long: int
    end_position_lat: int
    end_position_long: int
    max_speed: float
    avg_vert_speed: float
    end_time: Union[int, datetime]
    total_calories: int
    start_elevation: float
    # Active time of split rounds
    active_time: float
    total_moving_time: float



class SplitSummaryMesg(FitMesg, total=False):
    message_index: MessageIndex
    split_type: SplitType
    num_splits: int
    total_timer_time: float
    total_distance: float
    avg_speed: float
    max_speed: float
    total_ascent: int
    total_descent: int
    avg_heart_rate: int
    max_heart_rate: int
    avg_vert_speed: float
    total_calories: int
    # total active time in all split rounds
    active_time: float
    total_moving_time: float



class ClimbProMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    position_lat: int
    position_long: int
    climb_pro_event: ClimbProEvent
    climb_number: int
    climb_category: int
    current_dist: float



# Must be logged before developer field is used
class FieldDescriptionMesg(FitMesg, total=False):
    developer_data_index: int
    field_definition_number: int
    fit_base_type_id: FitBaseType
    field_name: StringValue
    array: int
    components: StringValue
    scale: int
    offset: int
    units: StringValue
    bits: StringValue
    accumulate: StringValue
    fit_base_unit_id: FitBaseUnit
    native_mesg_num: MesgNum
    native_field_num: int



# Must be logged before field description
class DeveloperDataIdMesg(FitMesg, total=False):
    developer_id: Union[int, List[Optional[int]]]
    application_id: Union[int, List[Optional[int]]]
    manufacturer_id: Manufacturer
    developer_data_index: int
    application_version: int



class CourseMesg(FitMesg, total=False):
    sport: Sport
    name: StringValue
    capabilities: CourseCapabilities
    sub_sport: SubSport



class CoursePointMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    position_lat: int
    position_long: int
    distance: float
    type: CoursePoint
    name: StringValue
    favorite: bool



# Unique Identification data for a segment file
class SegmentIdMesg(FitMesg, total=False):
    # Friendly name assigned to segment
    name: StringValue
    # UUID of the segment
    uuid: StringValue
    # Sport associated with the segment
    sport: Sport
    # Segment enabled for evaluation
    enabled: bool
    # Primary key of the user that created the segment
    user_profile_primary_key: int
    # ID of the device that created the segment
    device_id: int
    # Index for the Leader Board entry selected as the default race participant
    default_race_leader: int
    # Indicates if any segments should be deleted
    delete_status: SegmentDeleteStatus
    # Indicates how the segment was selected to be sent to the device
    selection_type: SegmentSelectionType



# Unique Identification data for an individual segment leader within a segment file
class SegmentLeaderboardEntryMesg(FitMesg, total=False):
    message_index: MessageIndex
    # Friendly name assigned to leader
    name: StringValue
    # Leader classification
    type: SegmentLeaderboardType
    # Primary user ID of this leader
    group_primary_key: int
    # ID of the activity associated with this leader time
    activity_id: int
    # Segment Time (includes pauses)
    segment_time: float
    # String version of the activity_id. 21 characters long, express in decimal
    activity_id_string: StringValue



# Navigation and race evaluation point for a segment decribing a point along the segment path and time it took each segment leader to reach that point
class SegmentPointMesg(FitMesg, total=False):
    message_index: MessageIndex
    position_lat: int
    position_long: int
    # Accumulated distance along the segment at the described point
    distance: float
    # Accumulated altitude along the segment at the described point
    altitude: float
    # Accumualted time each leader board member required to reach the described point. This value is zero for all leader board members at the starting point of the segment.
    leader_time: Union[float, List[Optional[float]]]
    # Accumulated altitude along the segment at the described point
    enhanced_altitude: float



class SegmentLapMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    event: Event
    event_type: EventType
    start_time: Union[int, datetime]
    start_position_lat: int
    start_position_long: int
    end_position_lat: int
    end_position_long: int
    # Time (includes pauses)
    total_elapsed_time: float
    # Timer Time (excludes pauses)
    total_timer_time: float
    total_distance: float
    total_cycles: int
    total_strokes: int
    total_calories: int
    # If New Leaf
    total_fat_calories: int
    avg_speed: float
    max_speed: float
    avg_heart_rate: int
    max_heart_rate: int
    # total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
    avg_cadence: int
    max_cadence: int
    # total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
    avg_power: int
    max_power: int
    total_ascent: int
    total_descent: int
    sport: Sport
    event_group: int
    # North east corner latitude.
    nec_lat: int
    # North east corner longitude.
    nec_long: int
    # South west corner latitude.
    swc_lat: int
    # South west corner latitude.
    swc_long: int
    name: StringValue
    normalized_power: int
    left_right_balance: LeftRightBalance100
    sub_sport: SubSport
    total_work: int
    avg_altitude: float
    max_altitude: float
    gps_accuracy: int
    avg_grade: float
    avg_pos_grade: float
    avg_neg_grade: float
    max_pos_grade: float
    max_neg_grade: float
    avg_temperature: int
    max_temperature: int
    total_moving_time: float
    avg_pos_vertical_speed: float
    avg_neg_vertical_speed: float
    max_pos_vertical_speed: float
    max_neg_vertical_speed: float
    time_in_hr_zone: Union[float, List[Optional[float]]]
    time_in_speed_zone: Union[float, List[Optional[float]]]
    time_in_cadence_zone: Union[float, List[Optional[float]]]
    time_in_power_zone: Union[float, List[Optional[float]]]
    repetition_num: int
    min_altitude: float
    min_heart_rate: int
    active_time: float
    wkt_step_index: MessageIndex
    sport_event: SportEvent
    avg_left_torque_effectiveness: float
    avg_right_torque_effectiveness: float
    avg_left_pedal_smoothness: float
    avg_right_pedal_smoothness: float
    avg_combined_pedal_smoothness: float
    status: SegmentLapStatus
    uuid: StringValue
    # fractional part of the avg_cadence
    avg_fractional_cadence: float
    # fractional part of the max_cadence
    max_fractional_cadence: float
    # fractional part of the total_cycles
    total_fractional_cycles: float
    front_gear_shift_count: int
    rear_gear_shift_count: int
    # Total time spent in the standing position
    time_standing: float
    # Number of transitions to the standing state
    stand_count: int
    # Average left platform center offset
    avg_left_pco: int
    # Average right platform center offset
    avg_right_pco: int
    # Average left power phase angles. Data value indexes defined by power_phase_type.
    avg_left_power_phase: Union[float, List[Optional[float]]]
    # Average left power phase peak angles. Data value indexes defined by power_phase_type.
    avg_left_power_phase_peak: Union[float, List[Optional[float]]]
    # Average right power phase angles. Data value indexes defined by power_phase_type.
    avg_right_power_phase: Union[float, List[Optional[float]]]
    # Average right power phase peak angles. Data value indexes defined by power_phase_type.
    avg_right_power_phase_peak: Union[float, List[Optional[float]]]
    # Average power by position. Data value indexes defined by rider_position_type.
    avg_power_position: Union[int, List[Optional[int]]]
    # Maximum power by position. Data value indexes defined by rider_position_type.
    max_power_position: Union[int, List[Optional[int]]]
    # Average cadence by position. Data value indexes defined by rider_position_type.
    avg_cadence_position: Union[int, List[Optional[int]]]
    # Maximum cadence by position. Data value indexes defined by rider_position_type.
    max_cadence_position: Union[int, List[Optional[int]]]
    # Manufacturer that produced the segment
    manufacturer: Manufacturer
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    total_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    total_flow: float
    # The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
    avg_grit: float
    # The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
    avg_flow: float
    # fractional part of total_ascent
    total_fractional_ascent: float
    # fractional part of total_descent
    total_fractional_descent: float
    enhanced_avg_altitude: float
    enhanced_max_altitude: float
    enhanced_min_altitude: float



# Summary of the unique segment and leaderboard information associated with a segment file. This message is used to compile a segment list file describing all segment files on a device. The segment list file is used when refreshing the contents of a segment file with the latest available leaderboard information.
class SegmentFileMesg(FitMesg, total=False):
    message_index: MessageIndex
    # UUID of the segment file
    file_uuid: StringValue
    # Enabled state of the segment file
    enabled: bool
    # Primary key of the user that created the segment file
    user_profile_primary_key: int
    # Leader type of each leader in the segment file
    leader_type: Union[SegmentLeaderboardType, List[Optional[SegmentLeaderboardType]]]
    # Group primary key of each leader in the segment file
    leader_group_primary_key: Union[int, List[Optional[int]]]
    # Activity ID of each leader in the segment file
    leader_activity_id: Union[int, List[Optional[int]]]
    # String version of the activity ID of each leader in the segment file. 21 characters long for each ID, express in decimal
    leader_activity_id_string: StringValue
    # Index for the Leader Board entry selected as the default race participant
    default_race_leader: int



class WorkoutMesg(FitMesg, total=False):
    message_index: MessageIndex
    sport: Sport
    capabilities: WorkoutCapabilities
    # number of valid steps
    num_valid_steps: int
    wkt_name: StringValue
    sub_sport: SubSport
    pool_length: float
    pool_length_unit: DisplayMeasure
    # Description of the workout
    wkt_description: StringValue



class WorkoutSessionMesg(FitMesg, total=False):
    message_index: MessageIndex
    sport: Sport
    sub_sport: SubSport
    num_valid_steps: int
    first_step_index: int
    pool_length: float
    pool_length_unit: DisplayMeasure



class WorkoutStepMesg(FitMesg, total=False):
    message_index: MessageIndex
    wkt_step_name: StringValue
    duration_type: WktStepDuration
    duration_value: int
    duration_time: float
    duration_distance: float
    duration_hr: WorkoutHr
    duration_calories: int
    # message_index of step to loop back to. Steps are assumed to be in the order by message_index. custom_name and intensity members are undefined for this duration type.
    duration_step: int
    duration_power: WorkoutPower
    duration_reps: int
    target_type: WktStepTarget
    target_value: int
    # speed zone (1-10);Custom =0;
    target_speed_zone: int
    # hr zone (1-5);Custom =0;
    target_hr_zone: int
    # Zone (1-?); Custom = 0;
    target_cadence_zone: int
    # Power Zone ( 1-7); Custom = 0;
    target_power_zone: int
    # # of repetitions
    repeat_steps: int
    repeat_time: float
    repeat_distance: float
    repeat_calories: int
    repeat_hr: WorkoutHr
    repeat_power: WorkoutPower
    target_stroke_type: SwimStroke
    custom_target_value_low: int
    custom_target_speed_low: float
    custom_target_heart_rate_low: WorkoutHr
    custom_target_cadence_low: int
    custom_target_power_low: WorkoutPower
    custom_target_value_high: int
    custom_target_speed_high: float
    custom_target_heart_rate_high: WorkoutHr
    custom_target_cadence_high: int
    custom_target_power_high: WorkoutPower
    intensity: Intensity
    notes: StringValue
    equipment: WorkoutEquipment
    exercise_category: ExerciseCategory
    exercise_name: int
    exercise_weight: float
    weight_display_unit: FitBaseUnit
    secondary_target_type: WktStepTarget
    secondary_target_value: int
    # speed zone (1-10);Custom =0;
    secondary_target_speed_zone: int
    # hr zone (1-5);Custom =0;
    secondary_target_hr_zone: int
    # Zone (1-?); Custom = 0;
    secondary_target_cadence_zone: int
    # Power Zone ( 1-7); Custom = 0;
    secondary_target_power_zone: int
    secondary_target_stroke_type: SwimStroke
    secondary_custom_target_value_low: int
    secondary_custom_target_speed_low: float
    secondary_custom_target_heart_rate_low: WorkoutHr
    secondary_custom_target_cadence_low: int
    secondary_custom_target_power_low: WorkoutPower
    secondary_custom_target_value_high: int
    secondary_custom_target_speed_high: float
    secondary_custom_target_heart_rate_high: WorkoutHr
    secondary_custom_target_cadence_high: int
    secondary_custom_target_power_high: WorkoutPower



class ExerciseTitleMesg(FitMesg, total=False):
    message_index: MessageIndex
    exercise_category: ExerciseCategory
    exercise_name: int
    wkt_step_name: StringValue



class ScheduleMesg(FitMesg, total=False):
    # Corresponds to file_id of scheduled workout / course.
    manufacturer: Manufacturer
    # Corresponds to file_id of scheduled workout / course.
    product: int
    favero_product: FaveroProduct
    garmin_product: GarminProduct
    # Corresponds to file_id of scheduled workout / course.
    serial_number: int
    # Corresponds to file_id of scheduled workout / course.
    time_created: Union[int, datetime]
    # TRUE if this activity has been started
    completed: bool
    type: Schedule
    scheduled_time: Union[int, datetime]



class TotalsMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    # Excludes pauses
    timer_time: int
    distance: int
    calories: int
    sport: Sport
    # Includes pauses
    elapsed_time: int
    sessions: int
    active_time: int
    sport_index: int



class WeightScaleMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    weight: float
    percent_fat: float
    percent_hydration: float
    visceral_fat_mass: float
    bone_mass: float
    muscle_mass: float
    basal_met: float
    physique_rating: int
    # ~4kJ per kcal, 0.25 allows max 16384 kcal
    active_met: float
    metabolic_age: int
    visceral_fat_rating: int
    # Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.
    user_profile_index: MessageIndex
    bmi: float



class BloodPressureMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    systolic_pressure: int
    diastolic_pressure: int
    mean_arterial_pressure: int
    map_3_sample_mean: int
    map_morning_values: int
    map_evening_values: int
    heart_rate: int
    heart_rate_type: HrType
    status: BpStatus
    # Associates this blood pressure message to a user. This corresponds to the index of the user profile message in the blood pressure file.
    user_profile_index: MessageIndex



class MonitoringInfoMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Use to convert activity timestamps to local time if device does not support time zone and daylight savings time correction.
    local_timestamp: Union[int, datetime]
    activity_type: Union[ActivityType, List[Optional[ActivityType]]]
    # Indexed by activity_type
    cycles_to_distance: Union[float, List[Optional[float]]]
    # Indexed by activity_type
    cycles_to_calories: Union[float, List[Optional[float]]]
    resting_metabolic_rate: int



class MonitoringMesg(FitMesg, total=False):
    # Must align to logging interval, for example, time must be 00:00:00 for daily log.
    timestamp: Union[int, datetime]
    # Associates this data to device_info message. Not required for file with single device (sensor).
    device_index: DeviceIndex
    # Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation
    calories: int
    # Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.
    distance: float
    # Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.
    cycles: float
    steps: int
    strokes: float
    active_time: float
    activity_type: ActivityType
    activity_subtype: ActivitySubtype
    activity_level: ActivityLevel
    distance_16: int
    cycles_16: int
    active_time_16: int
    # Must align to logging interval, for example, time must be 00:00:00 for daily log.
    local_timestamp: Union[int, datetime]
    # Avg temperature during the logging interval ended at timestamp
    temperature: float
    # Min temperature during the logging interval ended at timestamp
    temperature_min: float
    # Max temperature during the logging interval ended at timestamp
    temperature_max: float
    # Indexed using minute_activity_level enum
    activity_time: Union[int, List[Optional[int]]]
    active_calories: int
    # Indicates single type / intensity for duration since last monitoring message.
    current_activity_type_intensity: int
    timestamp_min_8: int
    timestamp_16: int
    heart_rate: int
    intensity: float
    duration_min: int
    duration: int
    ascent: float
    descent: float
    moderate_activity_minutes: int
    vigorous_activity_minutes: int
    # Wheelchair Pushes
    pushes: int



class MonitoringHrDataMesg(FitMesg, total=False):
    # Must align to logging interval, for example, time must be 00:00:00 for daily log.
    timestamp: Union[int, datetime]
    # 7-day rolling average
    resting_heart_rate: int
    # RHR for today only. (Feeds into 7-day average)
    current_day_resting_heart_rate: int



class Spo2DataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    reading_spo2: int
    reading_confidence: int
    # Mode when data was captured
    mode: Spo2MeasurementType



class HrMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    fractional_timestamp: float
    time256: float
    filtered_bpm: Union[int, List[Optional[int]]]
    event_timestamp: Union[float, List[Optional[float]]]
    event_timestamp_12: Union[int, List[Optional[int]]]



# Value from 1 to 100 calculated by FirstBeat
class StressLevelMesg(FitMesg, total=False):
    stress_level_value: int
    # Time stress score was calculated
    stress_level_time: Union[int, datetime]



class MaxMetDataMesg(FitMesg, total=False):
    # Time maxMET and vo2 were calculated
    update_time: Union[int, datetime]
    vo2_max: float
    sport: Sport
    sub_sport: SubSport
    max_met_category: MaxMetCategory
    # Indicates if calibrated data was used in the calculation
    calibrated_data: bool
    # Indicates if the estimate was obtained using a chest strap or wrist heart rate
    hr_source: MaxMetHeartRateSource
    # Indidcates if the estimate was obtained using onboard GPS or connected GPS
    speed_source: MaxMetSpeedSource



# Body battery data used for HSA custom data logging
class HsaBodyBatteryDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # Body battery level: [0,100] Blank: -16
    level: Union[int, List[Optional[int]]]
    # Body battery charged value
    charged: Union[int, List[Optional[int]]]
    # Body battery uncharged value
    uncharged: Union[int, List[Optional[int]]]



# HSA events
class HsaEventMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Event ID. Health SDK use only
    event_id: int



# Raw accelerometer data used for HSA custom data logging
class HsaAccelerometerDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Millisecond resolution of the timestamp
    timestamp_ms: int
    # Sampling Interval in Milliseconds
    sampling_interval: int
    # X-Axis Measurement
    accel_x: Union[float, List[Optional[float]]]
    # Y-Axis Measurement
    accel_y: Union[float, List[Optional[float]]]
    # Z-Axis Measurement
    accel_z: Union[float, List[Optional[float]]]
    # 32 kHz timestamp
    timestamp_32k: int



class HsaGyroscopeDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Millisecond resolution of the timestamp
    timestamp_ms: int
    # Sampling Interval in 32 kHz timescale
    sampling_interval: int
    # X-Axis Measurement
    gyro_x: Union[float, List[Optional[float]]]
    # Y-Axis Measurement
    gyro_y: Union[float, List[Optional[float]]]
    # Z-Axis Measurement
    gyro_z: Union[float, List[Optional[float]]]
    # 32 kHz timestamp
    timestamp_32k: int



# User's current daily step data used for HSA custom data logging
class HsaStepDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds. File start: 0xFFFFFFEF File stop: 0xFFFFFFEE
    processing_interval: int
    # Total step sum
    steps: Union[int, List[Optional[int]]]



# User's current SpO2 data used for HSA custom data logging
class HsaSpo2DataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # SpO2 Reading: [70,100] Blank: 240
    reading_spo2: Union[int, List[Optional[int]]]
    # SpO2 Confidence: [0,254]
    confidence: Union[int, List[Optional[int]]]



# User's current stress data used for HSA custom data logging
class HsaStressDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # Stress Level: [0,100] Off wrist: -1 Excess motion: -2 Not enough data: -3 Recovering from exercise: -4 Unidentified: -5 Blank: -16
    stress_level: Union[int, List[Optional[int]]]



# User's current respiration data used for HSA custom data logging
class HsaRespirationDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # Breaths / min: [1,100] Invalid: 255 Excess motion: 254 Off wrist: 253 Not available: 252 Blank: 2.4
    respiration_rate: Union[float, List[Optional[float]]]



# User's current heart rate data used for HSA custom data logging
class HsaHeartRateDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # Status of measurements in buffer - 0 indicates SEARCHING 1 indicates LOCKED
    status: int
    # Beats / min. Blank: 0
    heart_rate: Union[int, List[Optional[int]]]



# Configuration data for HSA custom data logging
class HsaConfigurationDataMesg(FitMesg, total=False):
    # Encoded configuration data
    timestamp: Union[int, datetime]
    # Encoded configuration data. Health SDK use only
    data: Union[int, List[Optional[int]]]
    # Size in bytes of data field
    data_size: int



# Wrist temperature data used for HSA custom data logging
class HsaWristTemperatureDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Processing interval length in seconds
    processing_interval: int
    # Wrist temperature reading
    value: Union[float, List[Optional[float]]]



class MemoGlobMesg(FitMesg, total=False):
    # Sequence number of memo blocks
    part_index: int
    # Deprecated. Use data field.
    memo: Union[int, List[Optional[int]]]
    # Message Number of the parent message
    mesg_num: MesgNum
    # Index of mesg that this glob is associated with.
    parent_index: MessageIndex
    # Field within the parent that this glob is associated with
    field_num: int
    # Block of utf8 bytes. Note, mutltibyte characters may be split across adjoining memo_glob messages.
    data: Union[int, List[Optional[int]]]



class SleepLevelMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    sleep_level: SleepLevel



class AntChannelIdMesg(FitMesg, total=False):
    channel_number: int
    device_type: int
    device_number: int
    transmission_type: int
    device_index: DeviceIndex



class AntRxMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    fractional_timestamp: float
    mesg_id: int
    mesg_data: Union[int, List[Optional[int]]]
    channel_number: int
    data: Union[int, List[Optional[int]]]



class AntTxMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    fractional_timestamp: float
    mesg_id: int
    mesg_data: Union[int, List[Optional[int]]]
    channel_number: int
    data: Union[int, List[Optional[int]]]



class ExdScreenConfigurationMesg(FitMesg, total=False):
    screen_index: int
    # number of fields in screen
    field_count: int
    layout: ExdLayout
    screen_enabled: bool



class ExdDataFieldConfigurationMesg(FitMesg, total=False):
    screen_index: int
    concept_field: int
    field_id: int
    concept_count: int
    display_type: ExdDisplayType
    title: StringValue



class ExdDataConceptConfigurationMesg(FitMesg, total=False):
    screen_index: int
    concept_field: int
    field_id: int
    concept_index: int
    data_page: int
    concept_key: int
    scaling: int
    data_units: ExdDataUnits
    qualifier: ExdQualifiers
    descriptor: ExdDescriptors
    is_signed: bool



class DiveSummaryMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    reference_mesg: MesgNum
    reference_index: MessageIndex
    # 0 if above water
    avg_depth: float
    # 0 if above water
    max_depth: float
    # Time since end of last dive
    surface_interval: int
    start_cns: int
    end_cns: int
    start_n2: int
    end_n2: int
    o2_toxicity: int
    dive_number: int
    bottom_time: float
    # Average pressure-based surface air consumption
    avg_pressure_sac: float
    # Average volumetric surface air consumption
    avg_volume_sac: float
    # Average respiratory minute volume
    avg_rmv: float
    # Time to reach deepest level stop
    descent_time: float
    # Time after leaving bottom until reaching surface
    ascent_time: float
    # Average ascent rate, not including descents or stops
    avg_ascent_rate: float
    # Average descent rate, not including ascents or stops
    avg_descent_rate: float
    # Maximum ascent rate
    max_ascent_rate: float
    # Maximum descent rate
    max_descent_rate: float
    # Time spent neither ascending nor descending
    hang_time: float



# Number of acclerometer zero crossings summed over the specified time interval
class AadAccelFeaturesMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Time interval length in seconds
    time: int
    # Total accelerometer energy in the interval
    energy_total: int
    # Count of zero crossings
    zero_cross_cnt: int
    # Instance ID of zero crossing algorithm
    instance: int
    # Total accelerometer time above threshold in the interval
    time_above_threshold: float



# Heart rate variability
class HrvMesg(FitMesg, total=False):
    # Time between beats
    time: Union[float, List[Optional[float]]]



# Array of heart beat intervals
class BeatIntervalsMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Milliseconds past date_time
    timestamp_ms: int
    # Array of millisecond times between beats
    time: Union[int, List[Optional[int]]]



class HrvStatusSummaryMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # 7 day RMSSD average over sleep
    weekly_average: float
    # Last night RMSSD average over sleep
    last_night_average: float
    # 5 minute high RMSSD value over sleep
    last_night_5_min_high: float
    # 3 week baseline, upper boundary of low HRV status
    baseline_low_upper: float
    # 3 week baseline, lower boundary of balanced HRV status
    baseline_balanced_lower: float
    # 3 week baseline, upper boundary of balanced HRV status
    baseline_balanced_upper: float
    status: HrvStatus



class HrvValueMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # 5 minute RMSSD
    value: float



# Raw Beat-to-Beat Interval values
class RawBbiMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Millisecond resolution of the timestamp
    timestamp_ms: int
    # 1 bit for gap indicator, 1 bit for quality indicator, and 14 bits for Beat-to-Beat interval values in whole-integer millisecond resolution
    data: Union[int, List[Optional[int]]]
    # Array of millisecond times between beats
    time: Union[int, List[Optional[int]]]
    # 1 = high confidence. 0 = low confidence. N/A when gap = 1
    quality: Union[int, List[Optional[int]]]
    # 1 = gap (time represents ms gap length). 0 = BBI data
    gap: Union[int, List[Optional[int]]]



class RespirationRateMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    # Breaths * 100 /min, -300 indicates invalid, -200 indicates large motion, -100 indicates off wrist
    respiration_rate: float



# Specifically used for XERO products.
class ChronoShotSessionMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    min_speed: float
    max_speed: float
    avg_speed: float
    shot_count: int
    projectile_type: ProjectileType
    grain_weight: float
    standard_deviation: float



# Specifically used for XERO products.
class ChronoShotDataMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    shot_speed: float
    shot_num: int



class TankUpdateMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    sensor: AntChannelId
    pressure: float



class TankSummaryMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    sensor: AntChannelId
    start_pressure: float
    end_pressure: float
    volume_used: float



class SleepAssessmentMesg(FitMesg, total=False):
    # Average of awake_time_score and awakenings_count_score. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    combined_awake_score: int
    # Score that evaluates the total time spent awake between sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    awake_time_score: int
    # Score that evaluates the number of awakenings that interrupt sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    awakenings_count_score: int
    # Score that evaluates the amount of deep sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    deep_sleep_score: int
    # Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    sleep_duration_score: int
    # Score that evaluates the amount of light sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    light_sleep_score: int
    # Total score that summarizes the overall quality of sleep, combining sleep duration and quality. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    overall_sleep_score: int
    # Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    sleep_quality_score: int
    # Score that evaluates stress and recovery during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    sleep_recovery_score: int
    # Score that evaluates the amount of REM sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    rem_sleep_score: int
    # Score that evaluates the amount of restlessness during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    sleep_restlessness_score: int
    # The number of awakenings during sleep.
    awakenings_count: int
    # Score that evaluates the sleep interruptions. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
    interruptions_score: int
    # Excludes stress during awake periods in the sleep window
    average_stress_during_sleep: float



class SleepDisruptionSeverityPeriodMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    severity: SleepDisruptionSeverity



class SleepDisruptionOvernightSeverityMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    severity: SleepDisruptionSeverity



class NapEventMesg(FitMesg, total=False):
    message_index: MessageIndex
    timestamp: Union[int, datetime]
    start_time: Union[int, datetime]
    start_timezone_offset: int
    end_time: Union[int, datetime]
    end_timezone_offset: int
    feedback: NapPeriodFeedback
    is_deleted: bool
    source: NapSource
    # The timestamp representing when this nap event was last updated
    update_timestamp: Union[int, datetime]



class SkinTempOvernightMesg(FitMesg, total=False):
    timestamp: Union[int, datetime]
    local_timestamp: Union[int, datetime]
    # The average overnight deviation from baseline temperature in degrees C
    average_deviation: float
    # The average 7 day overnight deviation from baseline temperature in degrees C
    average_7_day_deviation: float
    # Final overnight temperature value
    nightly_value: float



class PadMesg(FitMesg, total=False):
    pass



class FitMessages(TypedDict, total=False):
    """TypedDict containing all possible decoded FIT message lists, keyed by message type."""

    file_id_mesgs: List[FileIdMesg]
    file_creator_mesgs: List[FileCreatorMesg]
    timestamp_correlation_mesgs: List[TimestampCorrelationMesg]
    software_mesgs: List[SoftwareMesg]
    slave_device_mesgs: List[SlaveDeviceMesg]
    capabilities_mesgs: List[CapabilitiesMesg]
    file_capabilities_mesgs: List[FileCapabilitiesMesg]
    mesg_capabilities_mesgs: List[MesgCapabilitiesMesg]
    field_capabilities_mesgs: List[FieldCapabilitiesMesg]
    device_settings_mesgs: List[DeviceSettingsMesg]
    user_profile_mesgs: List[UserProfileMesg]
    hrm_profile_mesgs: List[HrmProfileMesg]
    sdm_profile_mesgs: List[SdmProfileMesg]
    bike_profile_mesgs: List[BikeProfileMesg]
    connectivity_mesgs: List[ConnectivityMesg]
    watchface_settings_mesgs: List[WatchfaceSettingsMesg]
    ohr_settings_mesgs: List[OhrSettingsMesg]
    time_in_zone_mesgs: List[TimeInZoneMesg]
    zones_target_mesgs: List[ZonesTargetMesg]
    sport_mesgs: List[SportMesg]
    hr_zone_mesgs: List[HrZoneMesg]
    speed_zone_mesgs: List[SpeedZoneMesg]
    cadence_zone_mesgs: List[CadenceZoneMesg]
    power_zone_mesgs: List[PowerZoneMesg]
    met_zone_mesgs: List[MetZoneMesg]
    training_settings_mesgs: List[TrainingSettingsMesg]
    dive_settings_mesgs: List[DiveSettingsMesg]
    dive_alarm_mesgs: List[DiveAlarmMesg]
    dive_apnea_alarm_mesgs: List[DiveApneaAlarmMesg]
    dive_gas_mesgs: List[DiveGasMesg]
    goal_mesgs: List[GoalMesg]
    activity_mesgs: List[ActivityMesg]
    session_mesgs: List[SessionMesg]
    lap_mesgs: List[LapMesg]
    length_mesgs: List[LengthMesg]
    record_mesgs: List[RecordMesg]
    event_mesgs: List[EventMesg]
    device_info_mesgs: List[DeviceInfoMesg]
    device_aux_battery_info_mesgs: List[DeviceAuxBatteryInfoMesg]
    training_file_mesgs: List[TrainingFileMesg]
    weather_conditions_mesgs: List[WeatherConditionsMesg]
    weather_alert_mesgs: List[WeatherAlertMesg]
    gps_metadata_mesgs: List[GpsMetadataMesg]
    camera_event_mesgs: List[CameraEventMesg]
    gyroscope_data_mesgs: List[GyroscopeDataMesg]
    accelerometer_data_mesgs: List[AccelerometerDataMesg]
    magnetometer_data_mesgs: List[MagnetometerDataMesg]
    barometer_data_mesgs: List[BarometerDataMesg]
    three_d_sensor_calibration_mesgs: List[ThreeDSensorCalibrationMesg]
    one_d_sensor_calibration_mesgs: List[OneDSensorCalibrationMesg]
    video_frame_mesgs: List[VideoFrameMesg]
    obdii_data_mesgs: List[ObdiiDataMesg]
    nmea_sentence_mesgs: List[NmeaSentenceMesg]
    aviation_attitude_mesgs: List[AviationAttitudeMesg]
    video_mesgs: List[VideoMesg]
    video_title_mesgs: List[VideoTitleMesg]
    video_description_mesgs: List[VideoDescriptionMesg]
    video_clip_mesgs: List[VideoClipMesg]
    set_mesgs: List[SetMesg]
    jump_mesgs: List[JumpMesg]
    split_mesgs: List[SplitMesg]
    split_summary_mesgs: List[SplitSummaryMesg]
    climb_pro_mesgs: List[ClimbProMesg]
    field_description_mesgs: List[FieldDescriptionMesg]
    developer_data_id_mesgs: List[DeveloperDataIdMesg]
    course_mesgs: List[CourseMesg]
    course_point_mesgs: List[CoursePointMesg]
    segment_id_mesgs: List[SegmentIdMesg]
    segment_leaderboard_entry_mesgs: List[SegmentLeaderboardEntryMesg]
    segment_point_mesgs: List[SegmentPointMesg]
    segment_lap_mesgs: List[SegmentLapMesg]
    segment_file_mesgs: List[SegmentFileMesg]
    workout_mesgs: List[WorkoutMesg]
    workout_session_mesgs: List[WorkoutSessionMesg]
    workout_step_mesgs: List[WorkoutStepMesg]
    exercise_title_mesgs: List[ExerciseTitleMesg]
    schedule_mesgs: List[ScheduleMesg]
    totals_mesgs: List[TotalsMesg]
    weight_scale_mesgs: List[WeightScaleMesg]
    blood_pressure_mesgs: List[BloodPressureMesg]
    monitoring_info_mesgs: List[MonitoringInfoMesg]
    monitoring_mesgs: List[MonitoringMesg]
    monitoring_hr_data_mesgs: List[MonitoringHrDataMesg]
    spo2_data_mesgs: List[Spo2DataMesg]
    hr_mesgs: List[HrMesg]
    stress_level_mesgs: List[StressLevelMesg]
    max_met_data_mesgs: List[MaxMetDataMesg]
    hsa_body_battery_data_mesgs: List[HsaBodyBatteryDataMesg]
    hsa_event_mesgs: List[HsaEventMesg]
    hsa_accelerometer_data_mesgs: List[HsaAccelerometerDataMesg]
    hsa_gyroscope_data_mesgs: List[HsaGyroscopeDataMesg]
    hsa_step_data_mesgs: List[HsaStepDataMesg]
    hsa_spo2_data_mesgs: List[HsaSpo2DataMesg]
    hsa_stress_data_mesgs: List[HsaStressDataMesg]
    hsa_respiration_data_mesgs: List[HsaRespirationDataMesg]
    hsa_heart_rate_data_mesgs: List[HsaHeartRateDataMesg]
    hsa_configuration_data_mesgs: List[HsaConfigurationDataMesg]
    hsa_wrist_temperature_data_mesgs: List[HsaWristTemperatureDataMesg]
    memo_glob_mesgs: List[MemoGlobMesg]
    sleep_level_mesgs: List[SleepLevelMesg]
    ant_channel_id_mesgs: List[AntChannelIdMesg]
    ant_rx_mesgs: List[AntRxMesg]
    ant_tx_mesgs: List[AntTxMesg]
    exd_screen_configuration_mesgs: List[ExdScreenConfigurationMesg]
    exd_data_field_configuration_mesgs: List[ExdDataFieldConfigurationMesg]
    exd_data_concept_configuration_mesgs: List[ExdDataConceptConfigurationMesg]
    dive_summary_mesgs: List[DiveSummaryMesg]
    aad_accel_features_mesgs: List[AadAccelFeaturesMesg]
    hrv_mesgs: List[HrvMesg]
    beat_intervals_mesgs: List[BeatIntervalsMesg]
    hrv_status_summary_mesgs: List[HrvStatusSummaryMesg]
    hrv_value_mesgs: List[HrvValueMesg]
    raw_bbi_mesgs: List[RawBbiMesg]
    respiration_rate_mesgs: List[RespirationRateMesg]
    chrono_shot_session_mesgs: List[ChronoShotSessionMesg]
    chrono_shot_data_mesgs: List[ChronoShotDataMesg]
    tank_update_mesgs: List[TankUpdateMesg]
    tank_summary_mesgs: List[TankSummaryMesg]
    sleep_assessment_mesgs: List[SleepAssessmentMesg]
    sleep_disruption_severity_period_mesgs: List[SleepDisruptionSeverityPeriodMesg]
    sleep_disruption_overnight_severity_mesgs: List[SleepDisruptionOvernightSeverityMesg]
    nap_event_mesgs: List[NapEventMesg]
    skin_temp_overnight_mesgs: List[SkinTempOvernightMesg]
    pad_mesgs: List[PadMesg]
