'''mesg_definition.py: Contains the _MesgDefinition class for building FIT message definitions.'''

###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.201.0Release
# Tag = production/release/21.201.0-0-g39a0a60c
############################################################################################


from . import fit as FIT
from .profile import Profile

# Reverse mapping: base type id -> field type string
_BASE_TYPE_TO_FIELD_TYPE = {v: k for k, v in FIT.FIELD_TYPE_TO_BASE_TYPE.items()}


class _MesgDefinition:
    """Represents a FIT message definition, built from a mesg_num and message data."""

    def __init__(self, mesg_num, mesg, field_descriptions=None):
        try:
            if mesg is None:
                raise ValueError("mesg is missing or None")
            if mesg_num is None:
                raise ValueError("mesg_num is missing or None")

            mesg_profile = Profile['messages'].get(mesg_num)
            if mesg_profile is None:
                raise ValueError(f"mesg_num: {mesg_num} could not be found in the Profile")

            self.global_message_number = mesg_num
            self.local_mesg_num = 0
            self.field_definitions = []
            self.developer_field_definitions = []

            for field_name in mesg:
                if field_name == 'mesg_num' or field_name == 'developer_fields':
                    continue
                if mesg[field_name] is None:
                    continue

                field_profile = None
                for _fnum, fp in mesg_profile['fields'].items():
                    if fp['name'] == field_name:
                        field_profile = fp
                        break

                if field_profile is None:
                    continue

                base_type = FIT.FIELD_TYPE_TO_BASE_TYPE.get(field_profile['base_type'])
                if base_type is None:
                    raise ValueError(f"Unknown base_type '{field_profile['base_type']}' for field '{field_name}'")

                base_type_def = FIT.BASE_TYPE_DEFINITIONS[base_type]

                if len(field_profile['components']) > 1:
                    scale = FIT.FIELD_DEFAULT_SCALE
                    offset = FIT.FIELD_DEFAULT_OFFSET
                else:
                    raw_scale = field_profile['scale']
                    raw_offset = field_profile['offset']
                    scale = raw_scale[0] if isinstance(raw_scale, list) and raw_scale else raw_scale if raw_scale is not None else FIT.FIELD_DEFAULT_SCALE
                    offset = raw_offset[0] if isinstance(raw_offset, list) and raw_offset else raw_offset if raw_offset is not None else FIT.FIELD_DEFAULT_OFFSET

                self.field_definitions.append({
                    'name': field_name,
                    'num': field_profile['num'],
                    'size': self._field_size(mesg[field_name], base_type_def),
                    'base_type': base_type,
                    'base_type_endian_flag': base_type_def['endian_flag'],
                    'type': field_profile['type'],
                    'scale': scale,
                    'offset': offset,
                    'components': field_profile['components'],
                })

            # Developer fields
            dev_fields = mesg.get('developer_fields')
            if dev_fields:
                for key in sorted(dev_fields.keys()):
                    dev_data_id_mesg, field_desc_mesg = self._field_description_for_key(field_descriptions, key)

                    fit_base_type_id = field_desc_mesg['fit_base_type_id'] & FIT.BASE_TYPE_MASK
                    base_type_def = FIT.BASE_TYPE_DEFINITIONS[fit_base_type_id]

                    self.developer_field_definitions.append({
                        'key': key,
                        'base_type': fit_base_type_id,
                        'field_definition_number': field_desc_mesg['field_definition_number'],
                        'size': self._field_size(dev_fields[key], base_type_def),
                        'developer_data_index': dev_data_id_mesg['developer_data_index'],
                        'type': _BASE_TYPE_TO_FIELD_TYPE.get(base_type_def['type'], 'uint8'),
                        'scale': FIT.FIELD_DEFAULT_SCALE,
                        'offset': FIT.FIELD_DEFAULT_OFFSET,
                        'components': [],
                    })

            if len(self.field_definitions) == 0:
                raise ValueError("No valid fields were found in the message")

            for fd in self.field_definitions:
                if fd['size'] > FIT.MAX_FIELD_SIZE:
                    raise ValueError(f"Some field sizes are greater than {FIT.MAX_FIELD_SIZE}")
            
            for dfd in self.developer_field_definitions:
                if dfd['size'] > FIT.MAX_FIELD_SIZE:
                    raise ValueError(f"Developer field size for key '{dfd['key']}' is greater than {FIT.MAX_FIELD_SIZE}")

        except ValueError:
            raise
        except Exception as e:
            raise ValueError(f"Could not construct MesgDefinition from Message: {e}") from e

    def write(self, output):
        """Write this message definition to the output stream."""
        header_byte = FIT.MESG_DEFINITION_MASK | (self.local_mesg_num & FIT.LOCAL_MESG_NUM_MASK)
        if len(self.developer_field_definitions) > 0:
            header_byte |= FIT.DEV_DATA_MASK

        output.write_uint8(header_byte)
        output.write_uint8(0x00)  # Reserved
        output.write_uint8(FIT.ARCH_LITTLE_ENDIAN)
        output.write_uint16(self.global_message_number)
        output.write_uint8(len(self.field_definitions))

        for fd in self.field_definitions:
            output.write_uint8(fd['num'])
            output.write_uint8(fd['size'])
            output.write_uint8(fd['base_type'] | fd['base_type_endian_flag'])

        if len(self.developer_field_definitions) > 0:
            output.write_uint8(len(self.developer_field_definitions))
            for dfd in self.developer_field_definitions:
                output.write_uint8(dfd['field_definition_number'])
                output.write_uint8(dfd['size'])
                output.write_uint8(dfd['developer_data_index'])

    def equals(self, other):
        """Check if two message definitions are equivalent."""
        if (self.global_message_number != other.global_message_number
                or len(self.field_definitions) != len(other.field_definitions)
                or len(self.developer_field_definitions) != len(other.developer_field_definitions)):
            return False

        for lhs in self.field_definitions:
            found = any(
                lhs['num'] == rhs['num']
                and lhs['size'] == rhs['size']
                and lhs['base_type'] == rhs['base_type']
                for rhs in other.field_definitions
            )
            if not found:
                return False

        for lhs in self.developer_field_definitions:
            found = any(
                lhs['field_definition_number'] == rhs['field_definition_number']
                and lhs['size'] == rhs['size']
                and lhs['developer_data_index'] == rhs['developer_data_index']
                for rhs in other.developer_field_definitions
            )
            if not found:
                return False

        return True

    @staticmethod
    def _field_size(value, base_type_def):
        """Calculate the field size in bytes."""
        values = value if isinstance(value, list) else [value]

        if base_type_def['type'] == FIT.BASE_TYPE['STRING']:
            total = 0
            for value in values:
                total += len(value.encode('utf-8')) + 1
            return total

        return base_type_def['size'] * len(values)

    @staticmethod
    def _field_description_for_key(field_descriptions, key):
        """Look up and validate the developer field description for the given key."""
        try:
            if field_descriptions is None:
                raise ValueError("no developer data field descriptions provided")

            desc = field_descriptions.get(key)
            if desc is None:
                raise ValueError(f"could not find a developer field description for key {key}")

            dev_data_id_mesg = desc.get('developer_data_id_mesg')
            field_desc_mesg = desc.get('field_description_mesg')

            if dev_data_id_mesg is None or field_desc_mesg is None:
                raise ValueError(f"could not find a developer field description for key {key}")

            errors = []
            if field_desc_mesg.get('fit_base_type_id') is None:
                errors.append(f"field_description_mesg fit_base_type_id is {field_desc_mesg.get('fit_base_type_id')}")
            if field_desc_mesg.get('field_definition_number') is None:
                errors.append(f"field_description_mesg field_definition_number is {field_desc_mesg.get('field_definition_number')}")
            if field_desc_mesg.get('developer_data_index') is None:
                errors.append(f"field_description_mesg developer_data_index is {field_desc_mesg.get('developer_data_index')}")
            if dev_data_id_mesg.get('developer_data_index') is None:
                errors.append(f"developer_data_id_mesg developer_data_index is {dev_data_id_mesg.get('developer_data_index')}")

            if dev_data_id_mesg.get('developer_data_index') != field_desc_mesg.get('developer_data_index'):
                errors.append(
                    f"developerDataIndex values do not match: "
                    f"{dev_data_id_mesg.get('developer_data_index')} != {field_desc_mesg.get('developer_data_index')}"
                )

            if errors:
                raise ValueError(f"missing or invalid values in the field description: {', '.join(errors)}")

            return dev_data_id_mesg, field_desc_mesg

        except ValueError:
            raise
        except Exception as e:
            raise ValueError(f"invalid field description for key {key}") from e
