###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.212.0Release
# Tag = production/release/21.212.0-0-g0676a0e3
############################################################################################


from typing import Any, Dict, List, Optional

from .encoder import FieldDescription
from .output_stream import _OutputStream

class _MesgDefinition:
    global_message_number: int
    local_mesg_num: int
    field_definitions: List[Dict[str, Any]]
    developer_field_definitions: List[Dict[str, Any]]

    def __init__(
        self,
        mesg_num: int,
        mesg: Dict[str, Any],
        field_descriptions: Optional[Dict[int, FieldDescription]] = None,
    ) -> None: ...
    def write(self, output: _OutputStream) -> None: ...
    def equals(self, other: "_MesgDefinition") -> bool: ...
