'''output_stream.py: Contains the _OutputStream helper class for writing FIT binary data.'''

###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.200.0Release
# Tag = production/release/21.200.0-0-g28b5705d
############################################################################################


import struct

from . import fit as FIT

_FLOAT_TYPE_CODES = ('f', 'd')
_STRING_TYPE_CODE = 's'


class _OutputStream:
    """A byte buffer that supports writing FIT base types in little-endian order."""

    def __init__(self):
        self._buffer = bytearray()

    @property
    def length(self):
        return len(self._buffer)

    @property
    def data(self):
        return bytes(self._buffer)

    def write_uint8(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT8'])

    def write_uint16(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT16'])

    def write_uint32(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT32'])

    def write_uint64(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT64'])

    def write_sint8(self, value):
        return self.write(value, FIT.BASE_TYPE['SINT8'])

    def write_sint16(self, value):
        return self.write(value, FIT.BASE_TYPE['SINT16'])

    def write_sint32(self, value):
        return self.write(value, FIT.BASE_TYPE['SINT32'])

    def write_sint64(self, value):
        return self.write(value, FIT.BASE_TYPE['SINT64'])

    def write_float32(self, value):
        return self.write(value, FIT.BASE_TYPE['FLOAT32'])

    def write_float64(self, value):
        return self.write(value, FIT.BASE_TYPE['FLOAT64'])

    def write_uint8z(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT8Z'])

    def write_uint16z(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT16Z'])

    def write_uint32z(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT32Z'])

    def write_uint64z(self, value):
        return self.write(value, FIT.BASE_TYPE['UINT64Z'])

    def write_byte(self, value):
        return self.write(value, FIT.BASE_TYPE['BYTE'])

    def write_enum(self, value):
        return self.write(value, FIT.BASE_TYPE['ENUM'])
    
    def write_string(self, text):
        """Write a string followed by a null terminator."""
        if isinstance(text, list):
            text = '\x00'.join(text)
        encoded = text.encode('utf-8')
        self._buffer.extend(encoded)
        self._buffer.append(0x00)

    def write_value(self, value, base_type):
        """Write a single value of the given base type."""
        base_type_def = FIT.BASE_TYPE_DEFINITIONS.get(base_type)
        if base_type_def is None:
            raise ValueError(f'Unsupported base type: {base_type}')

        if value is None:
            value = base_type_def['invalid']

        type_code = base_type_def['type_code']
        format = f'<{type_code}' if base_type_def['size'] > 1 else type_code

        # Truncate out-of-range integer values to fit the base type's bit width.
        if type_code not in _FLOAT_TYPE_CODES and type_code != _STRING_TYPE_CODE:
            bits = base_type_def['size'] * 8
            mask = (1 << bits) - 1
            value = int(value) & mask
            if base_type_def['signed'] and value >= (1 << (bits - 1)):
                value -= (1 << bits)

        self._buffer.extend(struct.pack(format, value))

    def write_values(self, values, base_type):
        """Write a list of values of the given base type."""
        for value in values:
            self.write_value(value, base_type)

    def write(self, value, base_type):
        """Write a single value or list of values, dispatching to string or numeric."""
        if base_type == FIT.BASE_TYPE['STRING']:
            self.write_string(value)
        else:
            values = value if isinstance(value, list) else [value]
            for v in values:
                self.write_value(v, base_type)

    def set_bytes(self, data, offset=0):
        """Overwrite bytes at the given offset."""
        end = offset + len(data)
        if end > len(self._buffer):
            self._buffer.extend(b'\x00' * (end - len(self._buffer)))
        self._buffer[offset:end] = data
