###########################################################################################
# Copyright 2026 Garmin International, Inc.
# Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
# may not use this file except in compliance with the Flexible and Interoperable Data
# Transfer (FIT) Protocol License.
###########################################################################################
# ****WARNING****  This file is auto-generated!  Do NOT edit this file.
# Profile Version = 21.213.0Release
# Tag = production/release/21.213.0-0-g9e10ea9c
############################################################################################


from datetime import datetime
from typing import Any, Dict, Optional

FIT_EPOCH_S: int

BASE_TYPE_TO_FIELD_TYPE: Dict[int, str]
FIELD_TYPE_TO_BASE_TYPE: Dict[str, int]

def convert_timestamp_to_datetime(timestamp: Optional[int]) -> datetime: ...
def convert_datetime_to_timestamp(value: datetime) -> int: ...
